### ISSUE TITLE
No such file or directory: 'conf/payloads.yml'

### ISSUE THREAD

**Issue by Meow-ops** [mitre/caldera#1438]
upon building the docker image or starting server.py from the cloned repository I get the following erro :

```
% docker run -p 7010:7010 -p 7011:7011 -p 7012:7012 -p 8888:8888 caldera:server

Traceback (most recent call last):
  File "server.py", line 78, in <module>
    BaseWorld.apply_config('payloads', BaseWorld.strip_yml('conf/payloads.yml')[0])
  File "/usr/src/app/app/utility/base_world.py", line 58, in strip_yml
    with open(path, encoding='utf-8') as seed:
FileNotFoundError: [Errno 2] No such file or directory: 'conf/payloads.yml'
```

**Comment by khyberspache** [comment]
We changed our .gitignore so this file wasn't force added.  Patch coming in a few seconds...

**Comment by khyberspache** [comment]
Let me know if you have any issues moving forwards
