### ISSUE TITLE
Multi-line Linux response causes error

### ISSUE THREAD

**Issue by scottctaylor12** [mitre/caldera#149]
When I use the sandcat client on Linux systems, I am able to run the "Identify active user" ability with no issues. When I check the results I see the one word/line response, "root". However, when I use abilities such as "Parse SSH known_hosts" or "Collect ARP details" I receive the following error:

```
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp_session/__init__.py", line 152, in factory
    response = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 96, in impl
    return await handler(request)
  File "/usr/src/app/plugins/sandcat/app/sand_api.py", line 35, in results
    data = json.loads(self.utility_svc.decode_bytes(await request.read()))
  File "/usr/local/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 134 (char 133)
ERROR:aiohttp.server:Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 410, in start
    await resp.prepare(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_response.py", line 300, in prepare
    return await self._start(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_response.py", line 608, in _start
    return await super()._start(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_response.py", line 367, in _start
    await writer.write_headers(status_line, headers)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 110, in write_headers
    self._write(buf)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
```

I believe that the issue is the sandcat Linux client cannot handle command responses that are multiple lines. I tested on Windows with the "Collect ARP details" and it showed multiple lines properly in the results. 

I see that the 54ndc47.sh file uses a python command so I tested on two machines that use python 2.7.5 and 3.7.0, but both failed to pass back multiple line command outputs.

I believe it is a multiple line issue, but what do you think?

**Comment by privateducky** [comment]
no, the majority of responses (linux and windows) are multiple lines. one thing of note on sandcat (linux) is that it is intended to work on /bin/bash shells not /bin/sh. there can be odd behavior with base64 encoding between these two shell types, which looks similar to the stack trace you pasted above. we will be putting warning about this in sandcat in the future.
