### ISSUE TITLE
Plugin issue

### ISSUE THREAD

**Issue by s1nglethr3ad** [mitre/caldera#1537]
/usr/bin/pip3
[+] Pip already installed
[-] Generating Random Values
[+] caldera random api_keys installed
[+] caldera random crypt_salt installed
[+] Random Values added to default.yml
[-] Installing on GO dependencies
[+] GO github installed
[+] GO oath2 installed
[-] Setting up Python venv
[+] Python virtualenv installed
[+] Caldera python venv installed
[+] Caldera python requirements installed
[-] Building documentation
Running Sphinx v3.0.1
Creating file _generated/app.api.rst.
Creating file _generated/app.api.packs.rst.
Creating file _generated/app.contacts.rst.
Creating file _generated/app.contacts.handles.rst.
Creating file _generated/app.learning.rst.
Creating file _generated/app.objects.rst.
Creating file _generated/app.objects.secondclass.rst.
Creating file _generated/app.service.rst.
Creating file _generated/app.utility.rst.
Creating file _generated/modules.rst.
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 25 source files that are out of date
updating environment: [new config] 25 added, 0 changed, 0 removed
/home/user/emulation/caldera/calderaenv/lib/python3.6/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document                            
  warn("Container node skipped: type={0}".format(mdnode.t))
reading sources... [100%] index                                                                                                                                              
WARNING: autodoc: failed to import module 'rest_api' from module 'app.api'; the following exception was raised:
No module named 'plugins.manx.app'
WARNING: autodoc: failed to import module 'contact_tcp' from module 'app.contacts'; the following exception was raised:
No module named 'plugins.manx.app'
WARNING: autodoc: failed to import module 'app_svc' from module 'app.service'; the following exception was raised:
No module named 'plugins.manx.app'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                                                               
/home/user/emulation/caldera/docs/Common-problems.md:26: WARNING: None:any reference target not found: What-is-an-ability
/home/user/emulation/caldera/docs/Server-configuration.md:37: WARNING: None:any reference target not found: What-is-a-plugin
/home/user/emulation/caldera/docs/The-REST-API.md:70: WARNING: None:any reference target not found: What-is-an-ability
/home/user/emulation/caldera/docs/The-REST-API.md:72: WARNING: None:any reference target not found: Plugins-sandcat
generating indices...  genindex py-modindexdone
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 7 warnings.

The HTML pages are in emulation/caldera/docs/_build.
[+] sphinx documentation installed
[+] Caldera environment built
[+] Start the server by copy pasting these commands into the terminal
    source calderaenv/bin/activate
    python server.py
user@ubuntu:~/emulation/caldera$ source calderaenv/bin/activate
(calderaenv) user@ubuntu:~/emulation/caldera$ python server.py 
Traceback (most recent call last):
  File "server.py", line 10, in <module>
    from app.api.rest_api import RestApi
  File "/home/user/emulation/caldera/app/api/rest_api.py", line 14, in <module>
    from app.service.app_svc import Error
  File "/home/user/emulation/caldera/app/service/app_svc.py", line 16, in <module>
    from app.contacts.contact_tcp import Tcp
  File "/home/user/emulation/caldera/app/contacts/contact_tcp.py", line 7, in <module>
    from plugins.manx.app.c_session import Session
ModuleNotFoundError: No module named 'plugins.manx.app'

I've been working on this for a couple of days and cannot figure out why the error keeps occurring.  Python3 version is 3.6.9.  Trying to install on Ubuntu 18.04.4.  Any help would be greatly appreciated, thanks!

**Comment by s1nglethr3ad** [comment]
My fault.  RTFM, I did not pull with --recursive for the plugins.  I was moving too fast trying to get it up and running.
