### ISSUE TITLE
dirhash.SymlinkRecursionError

### ISSUE THREAD

**Issue by br0kej** [mitre/caldera#1730]
Currently running into the following error using the docker-compose stand up option using the following command - `docker-compose -f docker-compose.yml up`

```caldera_1  | 2020-06-04 12:18:28 - WARNING (server.py:90 <module>) --insecure flag set. Caldera will use the default.yml config file.
caldera_1  | 2020-06-04 12:18:28 - INFO  (server.py:97 <module>) Using main config from conf/default.yml
caldera_1  | 2020-06-04 12:18:28 - DEBUG (selector_events.py:59 __init__) Using selector: EpollSelector
caldera_1  | 2020-06-04 12:18:29 - DEBUG (learning_svc.py:19 __init__) Loaded 2 parsers
caldera_1  | Traceback (most recent call last):
caldera_1  |   File "/usr/local/lib/python3.8/site-packages/dirhash/__init__.py", line 292, in _get_dirhash
caldera_1  |     return _get_dirhash_recursive(os.path.realpath(abspath), *args, **kwargs)
caldera_1  |   File "/usr/local/lib/python3.8/site-packages/dirhash/__init__.py", line 389, in _get_dirhash_recursive
caldera_1  |     sub_dirhash = _get_dirhash_recursive(sub_realpath, sub_relpath, **fwd_kwargs)
caldera_1  |   File "/usr/local/lib/python3.8/site-packages/dirhash/__init__.py", line 389, in _get_dirhash_recursive
caldera_1  |     sub_dirhash = _get_dirhash_recursive(sub_realpath, sub_relpath, **fwd_kwargs)
caldera_1  |   File "/usr/local/lib/python3.8/site-packages/dirhash/__init__.py", line 389, in _get_dirhash_recursive
caldera_1  |     sub_dirhash = _get_dirhash_recursive(sub_realpath, sub_relpath, **fwd_kwargs)
caldera_1  |   [Previous line repeated 2 more times]
caldera_1  |   File "/usr/local/lib/python3.8/site-packages/dirhash/__init__.py", line 364, in _get_dirhash_recursive
caldera_1  |     raise SymlinkRecursionError(
caldera_1  | dirhash.SymlinkRecursionError: Symlink recursion: Real path '/usr/src/app/lib/python3.8/site-packages/pkg_resources/__pycache__' was encountered at 'lib/python3.8/site-packages/pkg_resources/__pycache__' and then 'lib64/python3.8/site-packages/pkg_resources/__pycache__'.
caldera_1  | 
caldera_1  | During handling of the above exception, another exception occurred:
caldera_1  | 
caldera_1  | Traceback (most recent call last):
caldera_1  |   File "server.py", line 109, in <module>
caldera_1  |     app_svc = AppService(application=web.Application())
caldera_1  |   File "/usr/src/app/app/service/app_svc.py", line 37, in __init__
caldera_1  |     self.version = self.get_version()
caldera_1  |   File "/usr/src/app/app/utility/base_world.py", line 157, in get_version
caldera_1  |     calculated_md5 = dirhash.dirhash(path, 'md5', ignore=ignore, match=included_extensions)
caldera_1  |   File "/usr/local/lib/python3.8/site-packages/dirhash/__init__.py", line 175, in dirhash
caldera_1  |     dirhash = _get_dirhash(
caldera_1  |   File "/usr/local/lib/python3.8/site-packages/dirhash/__init__.py", line 294, in _get_dirhash
caldera_1  |     raise SymlinkRecursionError(
caldera_1  | dirhash.SymlinkRecursionError: Symlink recursion: Real path '/usr/src/app/lib/python3.8/site-packages/pkg_resources/__pycache__' was encountered at '/usr/src/app/lib/python3.8/site-packages/pkg_resources/__pycache__' and then '/usr/src/app/lib64/python3.8/site-packages/pkg_resources/__pycache__'.
caldera_caldera_1 exited with code 1
```

I've also replicated the process locally, pulling release 2.7.0, creating a venv, installing requirements.txt and then starting the server, and get the same error message.

**Comment by br0kej** [comment]
Spotted the issue. The docker container maps the local CALDERA directory in and I'd managed to create a misconfigured venv that dropped its contents into CALDERA directory rather than a new folder. . .
