### ISSUE TITLE
 error while attempting to bind on address [Any app contact or host IP Addresses]

### ISSUE THREAD

**Issue by Cyb3rWard0g** [mitre/caldera#1766]
Good evening Caldera team,

Is there anything I need to do to allow the binding of a private IP address to any of the app contact configs or even the host?

I am running my endpoint in an Azure VM and it has the static local private IP of 10.0.0.8 assigned to the VM. However. I cannot start the server beyond just `0.0.0.0` in the config file. After starting the server and updating the websocket app.contact IP address I get:

```
 2020-06-25 05:42:50 - ERROR (contact_websocket.py:19 start) WebSocket error: [Errno 99] error while attempting to bind on address ('10.0.0.8', 7012): cannot assign requested address
```

If I try to update the host only, I get the following to:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1062, in create_server
    sock.bind(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "server.py", line 105, in <module>
    run_tasks(services=app_svc.get_services())
  File "server.py", line 55, in run_tasks
    loop.run_until_complete(start_server())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "server.py", line 38, in start_server
    await web.TCPSite(runner, BaseWorld.get_config('host'), BaseWorld.get_config('port')).start()
  File "/home/caldera/.local/lib/python3.6/site-packages/aiohttp/web_runner.py", line 104, in start
    reuse_port=self._reuse_port)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 1066, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 99] error while attempting to bind on address ('10.0.0.8', 8888): cannot assign requested address
```

I starting the server as `root`. Also, I am doing this because of this issue: https://github.com/mitre/manx/issues/12 where whenever I start the server with the defaults `0.0.0.0`, I also get something similar in the Javascript console:

```
WebSocket connection to 'ws://0.0.0.0:7012/manx/669246' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

**Comment by wbooth** [comment]
@Cyb3rWard0g are you still having this issue?

**Comment by Cyb3rWard0g** [comment]
Hey @wbooth ! I have not tried it again since the creation of this issue. I can try again with latest master branch. It is related to this issues as I mentioned before: https://github.com/mitre/manx/issues/12#issuecomment-646461666 . I am not sure if you guys can test Caldera with manx in a separate windows endpoint. Please and thank you in advance!
