### ISSUE TITLE
Update on modifying abilities through yml files

### ISSUE THREAD

**Issue by alexgumo7** [mitre/caldera#1770]
Hi, sorry for the late response. I am creating this issue as a continuation of https://github.com/mitre/caldera/issues/1713#issuecomment-636830891.

Just to clarify, the documentation is currently in nav bar -> plugins -> fieldmanual.

Concerning the issue, the problem that I exposed on the last comment wasn't related to the documentation as the structure of the yml ability files remains the same in both master version and in the 2.6.6 release. The problem was that I was creating the custom abilities in `caldera/data/abilities` (the path that I was using in 2.6.6) but now, the abilitites are stored in `caldera/plugins/stockpile/data/abilities`.

I have been testing the update of the custom abilities and the problem of the timeout and the first executor not updating is not appearing so far. However, I've noticed that if you try to edit the yml file while caldera tries to reload the ability, it gives the following error and it does not update again:

```
caldera_1                    | Traceback (most recent call last):                                                                                                                             
caldera_1                    |   File "/usr/src/app/app/service/app_svc.py", line 159, in watch_ability_files                                                                       [475/1926]
caldera_1                    |     await self.get_service('data_svc').load_ability_file(filename=f, access=p.access)                                                                          
caldera_1                    |   File "/usr/src/app/app/service/data_svc.py", line 102, in load_ability_file                                                                                  
caldera_1                    |     for entries in self.strip_yml(filename):                                                                                                                   
caldera_1                    |   File "/usr/src/app/app/utility/base_world.py", line 67, in strip_yml                                                                                         
caldera_1                    |     return list(yaml.load_all(seed, Loader=yaml.FullLoader))                                                                                                   
caldera_1                    |   File "/usr/local/lib/python3.8/site-packages/yaml/__init__.py", line 127, in load_all                                                                        
caldera_1                    |     loader = Loader(stream)                                                                                                                                    
caldera_1                    |   File "/usr/local/lib/python3.8/site-packages/yaml/loader.py", line 24, in __init__                                                                           
caldera_1                    |     Reader.__init__(self, stream)                                                                                                                              
caldera_1                    |   File "/usr/local/lib/python3.8/site-packages/yaml/reader.py", line 85, in __init__                                                                           
caldera_1                    |     self.determine_encoding()
caldera_1                    |   File "/usr/local/lib/python3.8/site-packages/yaml/reader.py", line 124, in determine_encoding
caldera_1                    |     self.update_raw()
caldera_1                    |   File "/usr/local/lib/python3.8/site-packages/yaml/reader.py", line 178, in update_raw
caldera_1                    |     data = self.stream.read(size)
caldera_1                    |   File "/usr/local/lib/python3.8/codecs.py", line 322, in decode
caldera_1                    |     (result, consumed) = self._buffer_decode(data, self.errors, final)
caldera_1                    | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf8 in position 24: invalid start byte
```

Thank you very much.

**Comment by alexgumo7** [comment]
Hello again,

After further testing (this time in the release 2.7.0) I've noticed two other bad behaviours concerning the creation/update of abilities.

*First bad behaviour*:
I have custom abilities where I specify different commands for different executors. The following is a piece of the yml of the ability:

```
...
platforms:
    windows:
      psh,pwsh:
        command: |
          Get-ChildItem -Path C:\Users -Recurse -ErrorAction SilentlyContinue ...
    linux:
      sh:
        command: |
...
```

Then, if I check how the ability is actually created, the first executor is wrong, instead of being psh (windows), it is sh (linux):
![image](https://user-images.githubusercontent.com/23341546/86922034-5ced5180-c12c-11ea-9f1e-4cbbdf841ca8.png)
The executor and the platform is not correct but the command is correct. For some reason the platform and executor of the first one has been changed. The actual linux executor is correct with the appropriate command.

*Second bad behaviour*: 
The abilities that depend on payloads are not working correctly due to the incorrect creation of the abilities. Although in the following ability I am specifying a payload:

```
...
windows:
      psh,pwsh:
        command: |
          .\7za.exe a -spf ...
        payload: 7za.exe
...
```

When I check later how is the ability actually created:
![image](https://user-images.githubusercontent.com/23341546/86922554-1ea46200-c12d-11ea-888c-188d15251501.png)

There is no payload associated.

**Comment by alexgumo7** [comment]
Concerning the second bad behaviour, I was using the structure that it is defined in the [documentation:](https://caldera.readthedocs.io/en/latest/Learning-the-terminology.html)

```
platform:
      exec_1,exec_2:
        command: |
          <command>
        payload: <payload>
```

However, the structure that actually works is the one I found in the [documentation of initial access](https://caldera.readthedocs.io/en/latest/Initial-access.html#write-an-initial-access-ability):

```
platform:
      exec_1,exec_2:
        command: |
          <command>
        payloads: 
          - <payload>
```

**Comment by alexgumo7** [comment]
Regarding the first bad behaviour, the problem only happens in the GUI. If I check the parameters from the API, they are correct. Still, this should be corrected in the GUI.
