### ISSUE TITLE
 Adversary Creation

### ISSUE THREAD

**Issue by aldo1901** [mitre/caldera#1814]
I'm recently downloaded branch 2.7.0 into my Kali box and I seem to be having issues saving an Adversary. I can start the process of adding an adversary, but once I hit save and the console tells me to refresh the GUI, the newly created adversary is not in the dropdown. 

I have tried it using the master branch and it works just fine, but I was going by recommendations to use a branch release for less bugs. I also notice this error when using 2.7:

020-07-27 23:14:29 - DEBUG (data_svc.py:110 _load) ValidationError({'objective': ['Unknown field.']})
Traceback (most recent call last):
  File "/home/caldera/app/service/data_svc.py", line 105, in _load
    await self._load_adversaries(plug)
  File "/home/operator0/RedTeam/caldera/app/service/data_svc.py", line 115, in _load_adversaries
    adversary = Adversary.load(adv)
  File "/home/caldera/app/utility/base_object.py", line 81, in load
    return cls.schema.load(dict_obj)
  File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 723, in load
    data, many=many, partial=partial, unknown=unknown, postprocess=True
  File "/usr/local/lib/python3.7/site-packages/marshmallow/schema.py", line 904, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'objective': ['Unknown field.']}

This does not happen when using a non-version branch.

Thank You

**Comment by Changzhu1997** [comment]
Same thing happens here.  2.7.0 version on Win7
Mine is 
`2020-07-26 23:17:22 - DEBUG (data_svc.py:110 _load) IndexError('list index out o
f range',)
Traceback (most recent call last):
  File "C:\Users\syssec0\Desktop\caldera\app\service\data_svc.py", line 103, in
_load
    await self._verify_ability_set()
  File "C:\Users\syssec0\Desktop\caldera\app\service\data_svc.py", line 277, in
_verify_ability_set
    decoded_test = existing.replace_cleanup(clean_ability.cleanup[0], payload)
IndexError: list index out of range
2020-07-26 23:17:54 - DEBUG (data_svc.py:110 _load) IndexError('list index out o
f range',)
Traceback (most recent call last):
  File "C:\Users\syssec0\Desktop\caldera\app\service\data_svc.py", line 103, in
_load
    await self._verify_ability_set()
  File "C:\Users\syssec0\Desktop\caldera\app\service\data_svc.py", line 277, in
_verify_ability_set
    decoded_test = existing.replace_cleanup(clean_ability.cleanup[0], payload)
IndexError: list index out of range`

**Comment by wbooth** [comment]
Thank you this has been addressed and will included in the next release
