### ISSUE TITLE
Unble to start server

### ISSUE THREAD

**Issue by xsallowed** [mitre/caldera#1876]
I am getting following error whenever I try to start the server.py

Traceback (most recent call last):
  File "server.py", line 105, in <module>
    run_tasks(services=app_svc.get_services())
  File "server.py", line 46, in run_tasks
    loop.run_until_complete(app_svc.register_contacts())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/tahir/caldera/app/service/app_svc.py", line 139, in register_contacts
    contact_class = import_module(contact_module_name).Contact
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tahir/caldera/app/contacts/contact_tcp.py", line 7, in <module>
    from plugins.manx.app.c_session import Session
ModuleNotFoundError: No module named 'plugins.manx.app'

**Comment by jstevensog** [comment]
Same issue here.
Cheers

**Comment by unkempthenry** [comment]
This is most likely due to not using the `--recursive` option when you initially cloned caldera. 

There's a couple ways to fix it: 

*  Re-clone the repository with the `--recursive` option (check out the example command in our README to grab a release version) 
*  Have git to pull down the missing submodules to your existing repository: 

  ```
  cd /path/to/caldera
  git submodule update --init 
  ```

Hope this helps!

**Comment by alshaboti** [comment]
@unkempthenry it works after running `git submodule update --init`, thanks
