### ISSUE TITLE
Cannot start secure.py on CentOS 8 machine

### ISSUE THREAD

**Issue by jstevensog** [mitre/caldera#1893]
Hello,
Having issues getting caldera to run, now after several pulls of the main repo.
When starting server.py as a test, the following results.

$ python3.6 server.py --insecure
2020-09-30 11:27:03 - WARNING (server.py:82 <module>) --insecure flag set. Caldera will use the default.yml config file.
2020-09-30 11:27:03 - INFO  (server.py:89 <module>) Using main config from conf/default.yml
2020-09-30 11:27:05 - ERROR (base_world.py:147 check_requirement) FileNotFoundError(2, "No such file or directory: 'go'")
2020-09-30 11:27:05 - ERROR (app_svc.py:144 validate_requirement) go does not meet the minimum version of 1.11
Traceback (most recent call last):
  File "server.py", line 105, in <module>
    run_tasks(services=app_svc.get_services())
  File "server.py", line 46, in run_tasks
    loop.run_until_complete(app_svc.register_contacts())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/home/jhs/caldera/app/service/app_svc.py", line 139, in register_contacts
    contact_class = import_module(contact_module_name).Contact
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jhs/caldera/app/contacts/contact_tcp.py", line 7, in <module>
    from plugins.manx.app.c_session import Session
ModuleNotFoundError: No module named 'plugins.manx.app'

I have googled around and cannot find a method to fix this issue.
Any suggestions would be appreciated.
Caldera version commit d5e46d352151cef0ff9e33ea25c3899e415c45ec
Python3.6
All requirements.txt met and installed.

Cheers

**Comment by jstevensog** [comment]
Never mind.  RTFM.
