### ISSUE TITLE
Adversary Plugin In Latest Stable Prevents Server.py from starting

### ISSUE THREAD

**Issue by tek911** [mitre/caldera#203]
I believe there is an issue with the adversary plugin's references to config in the latest stable. I have added the appropriate lines to my caldera/conf/local.yml as such:
`host: 0.0.0.0 
port: 8888
terminal_host: 0.0.0.0
terminal_port: 8880
sockets:
  - 8880
planner: plugins.stockpile.app.sequential
stores:
  - plugins/stockpile/payloads
  - plugins/adversary/payloads
plugins:
  - stockpile
  - sandcat
  - gui
  - chain
  - adversary
users:
  admin: admin`

When i start caldera (sudo python3 server.py) i am greeted with the following error:
`Traceback (most recent call last):
  File "server.py", line 111, in <module>
    plugin_modules = build_plugins(cfg['plugins'])
  File "server.py", line 96, in build_plugins
    modules.append(import_module('plugins.%s.hook' % plug))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/containeradmin/git/stable/caldera/plugins/adversary/hook.py", line 3, in <module>
    import plugins.adversary.app.config as config
  File "/home/containeradmin/git/stable/caldera/plugins/adversary/app/config.py", line 6, in <module>
    from plugins.adversary.app.database.dao import Dao
  File "/home/containeradmin/git/stable/caldera/plugins/adversary/app/database/dao.py", line 1, in <module>
    from plugins.adversary.app.database.mongo import Mongo
  File "/home/containeradmin/git/stable/caldera/plugins/adversary/app/database/mongo.py", line 3, in <module>
    from plugins.adversary.app.database.model import Model
  File "/home/containeradmin/git/stable/caldera/plugins/adversary/app/database/model.py", line 1, in <module>
    from plugins.adversary.app.utility.general import nested_get
  File "/home/containeradmin/git/stable/caldera/plugins/adversary/app/utility/general.py", line 5, in <module>
    import plugins.adversary.app.config as config
AttributeError: module 'plugins.adversary.app' has no attribute 'config'`

I believe the /home/containeradmin/git/stable/caldera/plugins/adversary/app/utility/general.py had a bad import reference, i can get past it by changing the config import to be 'from plugins.adversary.app import config' however i get errors about references to the filestore which i do not understand the app enough to know what the proper reference is or where the store variable should be imported from. Any assistance here is appreciated and I can button it up and put in a pull request for the fix. 

`containeradmin@BASE-EV1:~/git/stable/caldera$ sudo python3 server.py 
                  _//     _//                           
                  _//     _//                           
   _///   _//     _//     _//   _//    _/ _///   _//    
 _//    _//  _//  _// _// _// _/   _//  _//    _//  _// 
_//    _//   _//  _//_/   _//_///// _// _//   _//   _// 
 _//   _//   _//  _//_/   _//_/         _//   _//   _// 
   _///  _// _///_/// _// _//  _////   _///     _// _///
                                                        

Enter help or go to https://0.0.0.0:8888 in a browser
...Created user: admin:admin
Traceback (most recent call last):
  File "server.py", line 123, in <module>
    main(services=services, host=cfg['host'], port=cfg['port'], sockets=cfg['sockets'], users=cfg['users'])
  File "server.py", line 78, in main
    loop.run_until_complete(init(host, port, services, users))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "server.py", line 62, in init
    await attach_plugins(app, services)
  File "server.py", line 42, in attach_plugins
    await plugin(app, services)
  File "/home/containeradmin/git/stable/caldera/plugins/adversary/hook.py", line 56, in initialize
    config.initialize_settings(config_path='plugins/adversary/conf/config.ini', filestore_path=store)`

**Comment by ghost** [comment]
@tek911 I have not been able to reproduce this. this looks like a PYTHONPATH related issue from the stack trace. my initial thought is this is related to running as sudo (if your path is set to your normal user). 

I would try running as your normal user and then ensuring the PYTHONPATH is set to the root of the CALDERA project (it should be automatically but some operating systems can be finicky and could require you to enter your PYTHONPATH environment variable manually).

I'm going to move this issue to the adversary plugin repository, as it's related to that.
