### ISSUE TITLE
custom adversary storage

### ISSUE THREAD

**Issue by zorovj** [mitre/caldera#2136]
Hello,

I have deployed the latest caldera version as a docker and I am trying to make the custom adversary profiles to be persistent of docker restarts. I have mounted a persistent volume to the 'data/' folder as that is where the .yml files are created for new adversary profiles/abilities. But only the abilities are getting saved in it and I am getting **'Internal sever error'** for adversaries.

Logs:

FileNotFoundError: [Errno 2] No such file or directory: 'data/adversaries/aeef880a-e1eb-4762-85e3-7d5814ad3e2b.yml'
--
  | 2021-04-26 13:44:56 - ERROR (rest_api.py:112 rest_core) FileNotFoundError(2, 'No such file or directory')
  | Traceback (most recent call last):
  | File "/usr/src/app/app/api/rest_api.py", line 108, in rest_core
  | return web.json_response(await options[request.method][index](data))
  | File "/usr/src/app/app/service/rest_svc.py", line 41, in persist_adversary
  | r.extend(await self._persist_adversary(access, adv))
  | File "/usr/src/app/app/service/rest_svc.py", line 470, in _persist_adversary
  | await self._save_and_refresh_item(file_path, Adversary, final, allowed)
  | File "/usr/src/app/app/service/rest_svc.py", line 578, in _save_and_refresh_item
  | await self.get_service('file_svc').save_file(file_path, yaml.dump(final, encoding='utf-8', sort_keys=False),
  | File "/usr/src/app/app/service/file_svc.py", line 63, in save_file
  | self._save(os.path.join(target_dir, filename), payload, encrypt)
  | File "/usr/src/app/app/service/file_svc.py", line 164, in _save
  | with open(filename, 'wb') as f:
  | FileNotFoundError: [Errno 2] No such file or directory: 'data/adversaries/6e3f0f02-07b3-49f8-8fe5-bd2406541fe4.yml'

Can you please help me with this?

**Comment by zorovj** [comment]
mounting separate volumes for each of the subfolders in data works.
