### ISSUE TITLE
User Training: Creating New User

### ISSUE THREAD

**Issue by Albert-Rop** [mitre/caldera#2197]
└─# python3 server.py         
2021-07-16 15:37:43 - INFO  (server.py:118 <module>) Using main config from conf/local.yml
2021-07-16 15:37:43 - WARNING (knowledge_svc.py:19 __init__) Unable to properly load knowledge service module app.utility.base_knowledge_svc ('module'). Reverting to default.
Traceback (most recent call last):
  File "/root/caldera/server.py", line 148, in <module>
    run_tasks(services=app_svc.get_services())
  File "/root/caldera/server.py", line 58, in run_tasks
    loop.run_until_complete(app_svc.register_contacts())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/root/caldera/app/service/app_svc.py", line 138, in register_contacts
    contact_class = import_module(contact_module_name).Contact
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/caldera/app/contacts/contact_tcp.py", line 7, in <module>
    from plugins.manx.app.c_session import Session
ModuleNotFoundError: No module named 'plugins.manx.app'

When I try to start the server after modifying the local.yml file with new user credentials, I get above Error.
Add new red-team user credentials, using "test" as both the username and password.

TASK 18: Adding New USer
Terminate the CALDERA server.
Edit the conf/local.yml file in your preferred text editor. If this file does not exist, ensure the CALDERA server is not run with the --insecure flag and run and terminate the server again.
Add the following entry to the users > red section: "test: test".
Re-run the server. Ensure the --fresh flag is not used.
Task completed.

**Comment by blackwidow0616** [comment]
This is likely due to the manx folder being empty. A possible fix for this would be to clone the manx repo. From `caldera/plugins`, you can run `git clone https://github.com/mitre/manx.git` to grab just the manx repo.

Also it might be worthwhile to double check your `caldera/conf/local.yml` to make sure manx is enabled or disabled as you wish.

**Comment by blackwidow0616** [comment]
Hopefully this resolves your issue. If you’re still having any problems, please feel free to re-open or start a new ticket. Thanks!
