### ISSUE TITLE
Traceback when running get_admin step

### ISSUE THREAD

**Issue by thibc4** [mitre/caldera#22]
Hello, thank you for this great project!

When trying to run **get_admin** step, I get  "KeyError:  'stdout '".

Configuration:
- Environment with 1 DC (Windows Server 2016) and 2 Workstations (Windows 10), caldera installed on each of them
- CALDERA is installed in Ubuntu 16.04 LTS 
- The starting victim is a workstation, and the Rat is started as a logon user.

The technique worked perfectly fine at first, but when I set up an Applocker rule to disable powershell.exe on the workstation (in order to counter the attack), I got this:

INFO:app.operation.operation:Running step get_admin
DEBUG:app.operation.operation_obj:Oops commandline was reported without a pid
INFO:app.server:Planner closed
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ide/caldera/caldera/app/server.py", line 165, in sigint_handler
    target()
  File "/home/ide/caldera/caldera/app/server.py", line 306, in planner_process
    loop.run_until_complete(start_operations(rebuild_mappings))
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/ide/caldera/caldera/app/updates.py", line 127, in start_operations
    await s.loop()
  File "/home/ide/caldera/caldera/app/operation/operation.py", line 299, in loop
    await self._perform_next_step()
  File "/home/ide/caldera/caldera/app/operation/operation.py", line 612, in _perform_next_step
    success = await next_step.action(*args)
  File "/home/ide/caldera/caldera/app/operation/operation_steps.py", line 151, in action
    parsers.powerview.getnetlocalgroupmember)
  File "/home/ide/caldera/caldera/app/operation/operation_obj.py", line 125, in execute_powershell
    return parser(ivcommand.outputs['stdout'])
  File "/home/ide/.local/lib/python3.5/site-packages/mongoengine/base/datastructures.py", line 30, in __getitem__
    value = super(BaseDict, self).__getitem__(key)
**KeyError: 'stdout'**

**Comment by NeosMeliodas** [comment]
Does your code validate that the result contains a key called 'stdout' before trying to access it ? (Question for Caldera)
