### ISSUE TITLE
ValueError: time data

### ISSUE THREAD

**Issue by Anas-Ba** [mitre/caldera#2474]
OS : Debian 11
Python version : 3.9.2

I think there's an issue with the Manx agent, I was able to launch some operations but I couldn't see results of each operation.

2022-02-07 14:10:26 - ERROR (contact_svc.py:142 _save) Unexpected error occurred while saving link - time data '2022-02-07 02:11:20' does not match format '%Y-%m-%dT%H:%M:%SZ'
Traceback (most recent call last):
  File "/home/rops/caldera/app/service/contact_svc.py", line 121, in _save
    link.agent_reported_time = self.get_timestamp_from_string(result.agent_reported_time)
  File "/home/rops/caldera/app/utility/base_world.py", line 87, in get_timestamp_from_string
    return datetime.strptime(datetime_str, date_format)
  File "/usr/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-02-07 02:11:20' does not match format '%Y-%m-%dT%H:%M:%SZ'

**Comment by d4rk-x0r** [comment]
Issue resolved 👍 , I had to switch to an ubuntu-server-20.04 with Python version : 3.8.10 with no errors so far.

**Comment by ArtificialErmine** [comment]
Glad to hear you managed to resolve the issue! Let us know if it crops back up, and we'll see how we can help.
