### ISSUE TITLE
More fun with commander.exe?

### ISSUE THREAD

**Issue by braimee** [mitre/caldera#26]
Hi there,

I just got up and running moments ago with Caldera and first just wanted to *thank you* as it's a great tool!  I'm using it for an endpoint protection evaluation/bake-off and it's nice to be able to see how the various products respond when I throw a bunch of suspicious behavior at them.

One thing I'm noticing right away is all the "fun" seems to get stopped by endpoint protection software as they catch the commander.exe file.  Is there a way I can try and obfuscate this .exe some more to see if I can get more success out of the attacks?  I'd like to test the (likely) scenario where a user runs something that's not caught by AV.  Yet I don't want to just flat out disable AV either.

Thanks,
Brian

**Comment by rtl4k** [comment]
I'm not an expert, but I'd say that the commander.exe should be whitelisted, at least, in the signature based detection engine.

We would like to know if the TTP's are detected, not the malware itself, as we are assuming that an APT would use a new fully undetectable malware.

**Comment by dm-mitre** [comment]
@braimee the source for the RAT is here https://github.com/mitre/caldera-crater 
There isn't a lot of documentation but build steps should be straightforward. Let us know if you run into any issues. Anecdotally we've heard that people have had success by inserting random strings into the source code and recompiling. 

@rtl4k well said.

**Comment by braimee** [comment]
@rtl4k / @dm-mitre - thanks for all the info. 

I'm going to try the whitelist approach first for commander.exe.  I've done that on my test machine and then kicked off an operation with "the kitchen sink" thrown at the box.  It gets stuck on "bootstrap" and never moves any further.  At the PC, AV has not been triggered to block commander.exe.  I'll go back and refer to the docs, but are there logs I can look at to see where the issue is?

Thanks,
Brian

**Comment by dm-mitre** [comment]
@braimee let me know how it goes, all of the logs are output in the terminal that you start the caldera server on. If it hangs let me know what the last message was.

**Comment by braimee** [comment]
Hiya.  Ok so my Putty session timed out but the last thing I saw was:

````
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/helpers.py", line 554, in __get__
    return inst._cache[self.name]
KeyError: 'remote'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/helpers.py", line 521, in log
    for key, value in fmt_info:
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/helpers.py", line 513, in <genexpr>
    for key, method in self._methods)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/helpers.py", line 473, in _format_a
    ip = request.remote
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/helpers.py", line 556, in __get__
    val = self.wrapped(inst)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/web_request.py", line 321, in remote
    peername = transport.get_extra_info('peername')
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 306, in get_extra_info
    return self._ssl_protocol._get_extra_info(name, default)
  File "/usr/lib/python3.5/asyncio/sslproto.py", line 537, in _get_extra_info
    return self._transport.get_extra_info(name, default)
AttributeError: 'NoneType' object has no attribute 'get_extra_info'
````

I should add that on the client I believe the commander.exe (which I implemented as c:\meowmix.exe) was caught in mid-flight - even though I *thought* I whitelisted it - and got nuked:

<img width="324" alt="caldera2" src="https://user-images.githubusercontent.com/17596787/38327227-5af0eb76-380d-11e8-9e2d-71082175e169.PNG">

I'm guessing that's what's causing my operation to halt, as here's what I see on the Caldera console:

<img width="249" alt="caldera" src="https://user-images.githubusercontent.com/17596787/38327251-6b596eca-380d-11e8-9269-e867655647a6.PNG">

Should the operation timeout by default after a certain amount of time?  Just curious.

I'm going to try re-whitelisting c:\meowmix.exe and launch again to see if I get better luck.

**Comment by braimee** [comment]
Hey, just one more observation as I'm troubleshooting this.  I cancelled the hung operation, did a `cagent.exe restart` on the IGW-DESKTOP02 and tried re-running the same operation.  It wouldn't fire - got hung right out of the gate.  I restarted Caldera server and re-ran the same op and then it ran just fine.  Not sure if you want any artifacts to troubleshoot that behavior.  

Not a big deal, but it seems like Caldera might not be cleanly terminating an operation if it's interrupted mid-flight.

**Comment by dm-mitre** [comment]
@braimee the stacktrace that you posted is an unrelated bug in Python that was fixed in 3.5.4, although its purely cosmetic in this case so that doesn't point to anything going wrong

So yeah if the RAT gets deleted that would be a problem :) 

There isn't a timeout, so if the operation gets hung like that the way to recover is 1) cancel the operation then 2) restart the python process. That should allow it to progress to the cleanup phase.

**Comment by braimee** [comment]
Thanks much!  Ok we whitelisted the RAT and were able to complete our testing.  Again, AWESOME work.  Love this tool.  And no problem on simply restarting Caldera, that got me up and going no problem.  Have a great week!

Brian

**Comment by braimee** [comment]
Hey on a side note just wanted to share that I talked about Caldera in my podcast this week, and wrote up a "quick start" guide for Caldera as well (your documentation is great, I just like having everything in a one-sheeter).  Let me know if I should post the links - I don't like to do that unless I ask first.

**Comment by davidfsec** [comment]
Would love the links Brian!

Great work!

Dave

**Comment by braimee** [comment]
Ok cool!  So the podcast episode where I mention Caldera is here: https://7ms.us/7ms-305-evaluating-endpoint-protection-solutions-part-2/.  And then my quick start guide is here http://bpatty.rocks/#!blue_team/caldera.md.  Thanks again for your great work on this awesome tool.
