### ISSUE TITLE
how solve this ?

### ISSUE THREAD

**Issue by davian27** [mitre/caldera#2626]
py -3 -m pip install -U discord.py

Collecting discord.py
  Using cached discord.py-1.7.3-py3-none-any.whl (786 kB)
Collecting aiohttp<3.8.0,>=3.6.0
  Using cached aiohttp-3.7.4.post0.tar.gz (1.1 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: attrs>=17.3.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py) (21.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py) (6.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from aiohttp<3.8.0,>=3.6.0->discord.py) (1.7.2)
Collecting async-timeout<4.0,>=3.0
  Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)
Collecting chardet<5.0,>=2.0
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting typing-extensions>=3.6.5
  Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
Requirement already satisfied: idna>=2.0 in c:\users\user\appdata\local\programs\python\python310\lib\site-packages (from yarl<2.0,>=1.0->aiohttp<3.8.0,>=3.6.0->discord.py) (3.3)
Building wheels for collected packages: aiohttp
  Building wheel for aiohttp (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe' 'C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\user\AppData\Local\Temp\tmpl2fg6yo3'
       cwd: C:\Users\user\AppData\Local\Temp\pip-install-5eoe8t7e\aiohttp_f744d2bc7dc74cd6ad22d28c22830f3b
  Complete output (190 lines):
  C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\config\setupcfg.py:463: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.
    warnings.warn(msg, warning_class)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-cpython-310
  creating build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\abc.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\base_protocol.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\client.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\client_exceptions.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\client_proto.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\client_reqrep.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\client_ws.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\connector.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\cookiejar.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\formdata.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\frozenlist.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\hdrs.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\helpers.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\http.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\http_exceptions.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\http_parser.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\http_websocket.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\http_writer.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\locks.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\log.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\multipart.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\payload.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\payload_streamer.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\pytest_plugin.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\resolver.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\signals.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\streams.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\tcp_helpers.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\test_utils.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\tracing.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\typedefs.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\web.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\web_app.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\web_exceptions.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\web_fileresponse.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\web_log.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\web_middlewares.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\web_protocol.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\web_request.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\web_response.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\web_routedef.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\web_runner.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\web_server.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\web_urldispatcher.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\web_ws.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\worker.py -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\__init__.py -> build\lib.win-amd64-cpython-310\aiohttp
  running egg_info
  writing aiohttp.egg-info\PKG-INFO
  writing dependency_links to aiohttp.egg-info\dependency_links.txt
  writing requirements to aiohttp.egg-info\requires.txt
  writing top-level names to aiohttp.egg-info\top_level.txt
  reading manifest file 'aiohttp.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'aiohttp' anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.pyd' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  warning: no previously-included files matching '*.lib' found anywhere in distribution
  warning: no previously-included files matching '*.dll' found anywhere in distribution
  warning: no previously-included files matching '*.a' found anywhere in distribution
  warning: no previously-included files matching '*.obj' found anywhere in distribution
  warning: no previously-included files found matching 'aiohttp\*.html'
  no previously-included directories found matching 'docs\_build'
  adding license file 'LICENSE.txt'
  writing manifest file 'aiohttp.egg-info\SOURCES.txt'
  copying aiohttp\_cparser.pxd -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\_find_header.c -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\_find_header.h -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\_find_header.pxd -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\_frozenlist.c -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\_frozenlist.pyx -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\_headers.pxi -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\_helpers.c -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\_helpers.pyi -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\_helpers.pyx -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\_http_parser.c -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\_http_parser.pyx -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\_http_writer.c -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\_http_writer.pyx -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\_websocket.c -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\_websocket.pyx -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\frozenlist.pyi -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\py.typed -> build\lib.win-amd64-cpython-310\aiohttp
  copying aiohttp\signals.pyi -> build\lib.win-amd64-cpython-310\aiohttp
  creating build\lib.win-amd64-cpython-310\aiohttp\.hash
  copying aiohttp\.hash\_cparser.pxd.hash -> build\lib.win-amd64-cpython-310\aiohttp\.hash
  copying aiohttp\.hash\_find_header.pxd.hash -> build\lib.win-amd64-cpython-310\aiohttp\.hash
  copying aiohttp\.hash\_frozenlist.pyx.hash -> build\lib.win-amd64-cpython-310\aiohttp\.hash
  copying aiohttp\.hash\_helpers.pyi.hash -> build\lib.win-amd64-cpython-310\aiohttp\.hash
  copying aiohttp\.hash\_helpers.pyx.hash -> build\lib.win-amd64-cpython-310\aiohttp\.hash
  copying aiohttp\.hash\_http_parser.pyx.hash -> build\lib.win-amd64-cpython-310\aiohttp\.hash
  copying aiohttp\.hash\_http_writer.pyx.hash -> build\lib.win-amd64-cpython-310\aiohttp\.hash
  copying aiohttp\.hash\_websocket.pyx.hash -> build\lib.win-amd64-cpython-310\aiohttp\.hash
  copying aiohttp\.hash\frozenlist.pyi.hash -> build\lib.win-amd64-cpython-310\aiohttp\.hash
  copying aiohttp\.hash\hdrs.py.hash -> build\lib.win-amd64-cpython-310\aiohttp\.hash
  copying aiohttp\.hash\signals.pyi.hash -> build\lib.win-amd64-cpython-310\aiohttp\.hash
  running build_ext
  building 'aiohttp._websocket' extension
  Traceback (most recent call last):
    File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 349, in <module>
      main()
    File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 331, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 248, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\build_meta.py", line 244, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\build_meta.py", line 229, in _build_with_temp_dir
      self.run_setup()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\build_meta.py", line 281, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
      exec(code, locals())
    File "<string>", line 152, in <module>
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 177, in setup
      return run_commands(dist)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 193, in run_commands
      dist.run_commands()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
      self.run_command(cmd)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
      super().run_command(command)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
      cmd_obj.run()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
      self.distribution.run_command(command)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
      super().run_command(command)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
      cmd_obj.run()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\command\build.py", line 24, in run
      super().run()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
      self.run_command(cmd_name)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
      self.distribution.run_command(command)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
      super().run_command(command)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
      cmd_obj.run()
    File "<string>", line 50, in run
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 459, in build_extensions
      self._build_extensions_serial()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 485, in _build_extensions_serial
      self.build_extension(ext)
    File "<string>", line 56, in build_extension
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 540, in build_extension
      objects = self.compiler.compile(
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 361, in compile
      self.initialize()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 241, in initialize
      vc_env = _get_vc_env(plat_spec)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\msvc.py", line 316, in msvc14_get_vc_env
      return _msvc14_get_vc_env(plat_spec)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\msvc.py", line 268, in _msvc14_get_vc_env
      vcvarsall, vcruntime = _msvc14_find_vcvarsall(plat_spec)
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\msvc.py", line 223, in _msvc14_find_vcvarsall
      _, best_dir = _msvc14_find_vc2017()
    File "C:\Users\user\AppData\Local\Temp\pip-build-env-sa1g4tsq\overlay\Lib\site-packages\setuptools\msvc.py", line 193, in _msvc14_find_vc2017
      path = subprocess.check_output([
    File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\run\__init__.py", line 145, in __new__
      process = cls.create_process(command, stdin, cwd=cwd, env=env, shell=shell)
    File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\run\__init__.py", line 121, in create_process
      shlex.split(command),
    File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\shlex.py", line 315, in split
      return list(lex)
    File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\shlex.py", line 300, in __next__
      token = self.get_token()
    File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\shlex.py", line 109, in get_token
      raw = self.read_token()
    File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\shlex.py", line 140, in read_token
      nextchar = self.instream.read(1)
  AttributeError: 'list' object has no attribute 'read'
  ----------------------------------------
  ERROR: Failed building wheel for aiohttp
Failed to build aiohttp
ERROR: Could not build wheels for aiohttp which use PEP 517 and cannot be installed directly

**Comment by clenk** [comment]
Hi, there is no discord.py in this repo so your issue seems unrelated and not something we can help with. However, Google may help you figure out your issue: https://www.google.com/search?q=shlex.py%22%2C+line+140%2C+in+read_token+nextchar+%3D+self.instream.read(1)+AttributeError%3A+%27list%27+object+has+no+attribute+%27read%27&rlz=1C1GCEU_enUS884US884&{google:acceptedSuggestion}oq=shlex.py%22%2C+line+140%2C+in+read_token+nextchar+%3D+self.instream.read(1)+AttributeError%3A+%27list%27+object+has+no+attribute+%27read%27
