### ISSUE TITLE
Several challenges in the training not completing.

### ISSUE THREAD

**Issue by kenvb** [mitre/caldera#2634]
So far there are these challenges, which I can't complete:
Agent filename
Bootstrap abilities
Contact points
Kill agent

running Python 3.8.9
and go version go1.19 darwin/amd64

Got today's version (cloned 3 hours ago +/-)

Here is the startup log, the error messages appear after a while, but i can't really link it to a specific action. I don't believe they are related to the issues i'm having.

KVB@KVB caldera % python3 server.py --insecure
2022-08-08 13:00:59 - WARNING (server.py:116 <module>) --insecure flag set. Caldera will use the default.yml config file.
2022-08-08 13:00:59 - INFO  (server.py:123 <module>) Using main config from conf/default.yml
2022-08-08 13:00:59 - INFO  (contact_gist.py:70 start) Invalid Github Gist personal API token provided. Gist C2 contact will not be started.
2022-08-08 13:00:59 - INFO  (tunnel_ssh.py:26 start) Generating temporary SSH private key. Was unable to use provided SSH private key
2022-08-08 13:01:00 - INFO  (logging.py:92 log) Creating SSH listener on 0.0.0.0, port 8022
2022-08-08 13:01:00 - INFO  (app_svc.py:116 load) Enabled plugin: debrief
2022-08-08 13:01:00 - INFO  (app_svc.py:116 load) Enabled plugin: response
2022-08-08 13:01:00 - INFO  (app_svc.py:116 load) Enabled plugin: access
2022-08-08 13:01:00 - INFO  (app_svc.py:116 load) Enabled plugin: manx
2022-08-08 13:01:00 - INFO  (app_svc.py:116 load) Enabled plugin: training
2022-08-08 13:01:00 - INFO  (app_svc.py:116 load) Enabled plugin: stockpile
2022-08-08 13:01:00 - INFO  (app_svc.py:116 load) Enabled plugin: atomic
2022-08-08 13:01:00 - INFO  (app_svc.py:116 load) Enabled plugin: fieldmanual
2022-08-08 13:01:00 - INFO  (app_svc.py:116 load) Enabled plugin: sandcat
2022-08-08 13:01:00 - INFO  (app_svc.py:116 load) Enabled plugin: compass
2022-08-08 13:01:00 - WARNING (warnings.py:109 _showwarnmsg) /Users/KVB/Library/Python/3.8/lib/python/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,

2022-08-08 13:01:00 - INFO  (server.py:741 start) serving on 0.0.0.0:2222
2022-08-08 13:01:00 - WARNING (app_svc.py:171 validate_requirement) upx does not meet the minimum version of 0.0.0. Upx is an optional dependency which adds more functionality. 
2022-08-08 13:01:02 - INFO  (server.py:71 run_tasks) All systems ready.
2022-08-08 13:01:02 - INFO  (hook.py:58 build_docs) Docs built successfully.

2022-08-08 13:01:45 - ERROR (contact_tcp.py:93 send) Expecting value: line 2 column 1 (char 1)
Traceback (most recent call last):
  File "/Users/KVB/caldera/caldera/app/contacts/contact_tcp.py", line 90, in send
    response = json.loads(response)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by kenvb** [comment]
Ok. It seems they weren't completing because I hadn't done the "Update agent" test. I didn't realize the order was to be strictly followed!
