### ISSUE TITLE
New "Guided" planner has several errors

### ISSUE THREAD

**Issue by L015H4CK** [mitre/caldera#2660]
**Describe the bug**
Starting an operation with the guided planner results in several errors.

**To Reproduce**
1. Fresh install CALDERA 4.1.0 and start server
2. Create Operation with new guided planner
3. See error output

**Expected behavior**
The operation should run successfully without errors.

**Desktop:**
 - OS: Tested on Ubuntu 18.04 and Kali Linux 2022.2
 - Browser: Firefox
 - Version. 4.10

**Additional context**
I was very happy when I saw that two new planners were released in version 4.1.0, as I am also currently working on implementing some new planners (I hope I will be able to get in touch with you soon to publish them or at least post some information about them).

I tested everything on my Ubuntu host and my research Kali Linux VM. The errors were the same for both environments.

The first error were missing Python packages (networkx, numpy). Installing these packages with pip fixed the errors ("No module named (...)."). Are these still missing in the requirements.txt?

After installing the missing packages, the following error occured. I used the new Everyting Bagel adversary with the default objective and the guided planner.

```
Traceback (most recent call last):
  File "/<path>/vcaldera-4.1.0/caldera/app/objects/secondclass/c_executor.py", line 79, in __getattr__
    return super().__getattribute__('additional_info')[item]
KeyError: 'test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/<path>/vcaldera-4.1.0/caldera/app/objects/c_operation.py", line 341, in run
    await self.cede_control_to_planner(services)
  File "/<path>/vcaldera-4.1.0/caldera/app/objects/c_operation.py", line 331, in cede_control_to_planner
    await planner.execute()
  File "/<path>/vcaldera-4.1.0/caldera/plugins/stockpile/app/guided.py", line 137, in execute
    await self.planning_svc.execute_planner(self)
  File "/<path>/vcaldera-4.1.0/caldera/app/service/planning_svc.py", line 135, in execute_planner
    await getattr(planner, planner.next_bucket)()
  File "/<path>/vcaldera-4.1.0/caldera/plugins/stockpile/app/guided.py", line 140, in guided
    await self.execute_subop(ability_ids=self.ability_ids, goals=self.goals)
  File "/<path>/vcaldera-4.1.0/caldera/plugins/stockpile/app/guided.py", line 150, in execute_subop
    attack_graph = await self._build_attack_graph(ability_ids, agent)
  File "/<path>/vcaldera-4.1.0/caldera/plugins/stockpile/app/guided.py", line 219, in _build_attack_graph
    ability, attack_graph, operation_agent
  File "/<path>/vcaldera-4.1.0/caldera/plugins/stockpile/app/guided.py", line 285, in _input_fact_edges
    for fact in re.findall(FACT_REGEX, executor.test):
  File "/<path>/vcaldera-4.1.0/caldera/app/objects/secondclass/c_executor.py", line 81, in __getattr__
    raise AttributeError(item)
AttributeError: test
```

Next, I tried a custom objective and a custom adversary (Side note: When I tried to change the Objective of the Everything Bagel profile to a new custom objective, I received an error saying "Error saving profile."). The custom adversary had the ability "Find local users" which unlocks the fact "host.user.name" and the objective "host.user.name == <myname>" with count 1. The results are:

```2022-09-21 10:48:17 - ERROR (c_operation.py:344 run) Source host.user.name not in G
Traceback (most recent call last):
  File "<path>/vcaldera-4.1.0/caldera/app/objects/c_operation.py", line 341, in run
    await self.cede_control_to_planner(services)
  File "<path>/vcaldera-4.1.0/caldera/app/objects/c_operation.py", line 331, in cede_control_to_planner
    await planner.execute()
  File "<path>/vcaldera-4.1.0/caldera/plugins/stockpile/app/guided.py", line 137, in execute
    await self.planning_svc.execute_planner(self)
  File "<path>/vcaldera-4.1.0/caldera/app/service/planning_svc.py", line 135, in execute_planner
    await getattr(planner, planner.next_bucket)()
  File "<path>/vcaldera-4.1.0/caldera/plugins/stockpile/app/guided.py", line 140, in guided
    await self.execute_subop(ability_ids=self.ability_ids, goals=self.goals)
  File "<path>/vcaldera-4.1.0/caldera/plugins/stockpile/app/guided.py", line 160, in execute_subop
    attack_graph, goals=planner_goals
  File "<path>/vcaldera-4.1.0/caldera/plugins/stockpile/app/guided.py", line 331, in _build_distance_table
    shortest_path = nx.shortest_path(graph, target=goal.target)
  File "<path>/vcaldera-4.1.0/lib/python3.7/site-packages/networkx/algorithms/shortest_paths/generic.py", line 140, in shortest_path
    paths = nx.single_source_shortest_path(G, target)
  File "<path>/vcaldera-4.1.0/lib/python3.7/site-packages/networkx/algorithms/shortest_paths/unweighted.py", line 333, in single_source_shortest_path
    raise nx.NodeNotFound(f"Source {source} not in G")
networkx.exception.NodeNotFound: Source host.user.name not in G
```  

At this point, I do not know if I did something wrong or the planner does not work 100% correctly. Some more version info below.

Kali Host:
Python: 3.9.13

Ubuntu Host:
Python: 3.7.5

**Comment by djlawren** [comment]
Thank you for pointing this out!

On your first point regarding Python dependencies, the Stockpile plugin that the Guided planner is housed in has its own `requirements.txt` that contains `networkx` and `numpy`. Generally CALDERA plugins have their own `requirements.txt` if they have their own dependencies apart from Core.

I opened and linked a PR on Stockpile that should resolve at least the first bug that you pointed out. It was due to some executors seeming to be missing a command, which keeps the planner from being able to parse out its input fact dependencies. My changes just add an additional check that an executor has a command present before attempting to parse it.

The issue with the custom adversary/objective is due to there not being any valid executors for the "Find local users" ability. Have you been able to use that ability with your current set of agents using a different planner? I was just able to use the Guided planner to execute an operation on a custom adversary/objective like you described on my set of agents.

**Comment by L015H4CK** [comment]
Thank you for your answer!

1. Python dependencies: I see. Running `pip install -r plugins/stockpile/requirements.txt` worked as expected. Splitting the dependencies for the plugins is a great idea but I did not find a reference about plugin requirements in the installation guide. Is this intended? Maybe a simple sentence in the Installation section of the README could be added (e.g. after the pip requirement installation, "At this point, the pip requirements for the used plugins have to be install as well.").

2. Your changes work like a charm. Now the Everything Bagel works with the guided planner out of the box. (Note: for anyone who should have the same problem: you have to update the stockpile plugin manually since the changes are not in calderas master branch, yet.)

3. You are totally right, thanks for the input. At this point, I did something wrong. When creating my custom adversary profile via the UI (normally I create them as new files) and adding the ability, I only clicked "Save & Add" and did not click "Save Profile" afterwards.. So basically I was running the operation with an empty adversary profile. Still, is the exception intended or should it be caught at some point?

Also I would like to remind at this point, that changing the objective of the Everything Bagel results in an UI error saying "Error saving profile" when pressing the "Link objective" button. For other profiles it worked. Should I open a new issue for this?
