### ISSUE TITLE
Exception occurred:   File "/home/ale/.local/lib/python3.10/site-packages/sphinx/theming.py", line 199, in load_external_theme     theme_entry_points = entry_points(group='sphinx.html_themes') TypeError: entry_points() got an unexpected keyword argument 'group' The full traceback has been saved in /tmp/sphinx-err-xw_vtxn0.log, if you want to report the issue to the developers.

### ISSUE THREAD

**Issue by Aledangelo** [mitre/caldera#2669]
# Sphinx version: 5.1.1
# Python version: 3.10.7 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 3.0.3
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/ale/.local/lib/python3.10/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/ale/.local/lib/python3.10/site-packages/sphinx/application.py", line 261, in __init__
    self._init_builder()
  File "/home/ale/.local/lib/python3.10/site-packages/sphinx/application.py", line 333, in _init_builder
    self.builder.init()
  File "/home/ale/.local/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 248, in init
    self.init_templates()
  File "/home/ale/.local/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 299, in init_templates
    self.theme = theme_factory.create(themename)
  File "/home/ale/.local/lib/python3.10/site-packages/sphinx/theming.py", line 232, in create
    self.load_extra_theme(name)
  File "/home/ale/.local/lib/python3.10/site-packages/sphinx/theming.py", line 177, in load_extra_theme
    self.load_external_theme(name)
  File "/home/ale/.local/lib/python3.10/site-packages/sphinx/theming.py", line 199, in load_external_theme
    theme_entry_points = entry_points(group='sphinx.html_themes')
TypeError: entry_points() got an unexpected keyword argument 'group'

**Comment by clenk** [comment]
@Aledangelo I found [several](https://github.com/sphinx-doc/sphinx/issues/10479) [reports](https://github.com/pallets/flask/issues/4502) of people seeing a similar error using outdated versions of `importlib-metadata` but it isn't used in Python 3.10. I haven't encountered this error before.

Sphinx is only used in the documentation. You may be able to avoid this error by disabling the `fieldmanual` plugin (delete the line `- fieldmanual` from either `default.yml` or `local.yml`).
