### ISSUE TITLE
Can't access adversary part of the GUI

### ISSUE THREAD

**Issue by amonyphily** [mitre/caldera#276]
Hi,

I can't access to the adversary part of the webGUI, I get an error 500
(url http://:8888/plugin/adversary/gui)
And when I run my cagent.exe from client with the debug option I can see thoses errors :
```
Error 0xC00000FF - ERROR:caldera_agent.async_client:Uncaught exception retrieved in run_forever: Traceback (most recent call last):
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\async_client.py", line 49, in run_forever
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\async_client.py", line 63, in fail_pending
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 165, in jobs
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 72, in rest
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 104, in _raw_rest
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 44, in start
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 123, in _rest
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 217, in api
  File "C:\Program Files\Python35\lib\asyncio\futures.py", line 381, in __iter__
  File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 310, in _wakeup
  File "C:\Program Files\Python35\lib\asyncio\futures.py", line 294, in result
  File "C:\Program Files\Python35\lib\concurrent\futures\thread.py", line 55, in run
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 224, in urlread
  File "C:\Program Files\Python35\lib\urllib\request.py", line 163, in urlopen
  File "C:\Program Files\Python35\lib\urllib\request.py", line 466, in open
  File "C:\Program Files\Python35\lib\urllib\request.py", line 484, in _open
  File "C:\Program Files\Python35\lib\urllib\request.py", line 444, in _call_chain
  File "C:\Program Files\Python35\lib\urllib\request.py", line 1282, in http_open
  File "C:\Program Files\Python35\lib\urllib\request.py", line 1254, in do_open
  File "C:\Program Files\Python35\lib\http\client.py", line 1107, in request
  File "C:\Program Files\Python35\lib\http\client.py", line 1147, in _send_request
  File "C:\Program Files\Python35\lib\http\client.py", line 1084, in putheader
ValueError: Invalid header value b'AUTH=<head>\n    <title>Login | Access</title>\n\t<link rel="shortcut icon" type="image/png" href="/gui/img/favicon.png"/>\n\ConsoleCtrlHandler function failedTraceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\win32\lib\win32serviceutil.py", line 446, in _DebugCtrlHandler
OSError: [Errno 22] Invalid argument
t<link rel="stylesheet" href="/gui/css/shared.css" type="text/css">\n\t<link rel="stylesheet" href="/ 
```

I tried with SSL plugin and now get this error when trying cagent.exe debug:

```
c:\Program Files\cagent>cagent.exe debug
Debugging service cagent - press Ctrl+C to stop.
Info 0x400000FF - Created WinSvcLogHandler
Info 0x40001002 - The cagent service has started.
Error 0xC00000FF - ERROR:root:Task exception was never retrieved
future: <Task finished coro=<CalderaAgent.send_clients() done, defined at C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\agent.py:59> exception=RequestFailed()>
Traceback (most recent call last):
File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 240, in _step
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\agent.py", line 61, in send_clients
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 173, in clients
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 72, in rest
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 104, in rawrest
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 44, in start
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 143, in _rest
caldera_agent.rest_api.RequestFailed
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:root:Task exception was never retrieved
future: <Task finished coro=<Client.heartbeat() done, defined at C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\async_client.py:38> exception=RequestFailed()>
Traceback (most recent call last):
File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 240, in _step
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\async_client.py", line 40, in heartbeat
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 192, in stay_alive
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 72, in rest
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 104, in rawrest
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 44, in start
File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 143, in _rest
caldera_agent.rest_api.RequestFailed
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503
Error 0xC00000FF - ERROR:caldera_agent.async_client:Request failed with status: 503 
```
So the connection seems to be good but I can't locate the problem on the server side.
I have no logs on the server. Just the startup messages and admin connections.
(I put debug in local.yml)

Any help please ? Thank you !

**Comment by mikeyijdskfhsd** [comment]
I'm having the same problem, but only with the latest version of Caldera:
`
ERROR:caldera_agent.async_client:Uncaught exception retrieved in run_forever: Traceback (most recent call last):
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\async_client.py", line 49, in run_forever
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\async_client.py", line 63, in fail_pending
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 165, in jobs
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 72, in rest
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 104, in _raw_rest
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 44, in start
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 123, in _rest
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 217, in api
  File "C:\Program Files\Python35\lib\asyncio\futures.py", line 381, in __iter__
  File "C:\Program Files\Python35\lib\asyncio\tasks.py", line 310, in _wakeup
  File "C:\Program Files\Python35\lib\asyncio\futures.py", line 294, in result
  File "C:\Program Files\Python35\lib\concurrent\futures\thread.py", line 55, in run
  File "C:\Gitlab Runner\builds\f8e514af\0\caldera\caldera-agent\caldera_agent\rest_api.py", line 224, in urlread
  File "C:\Program Files\Python35\lib\urllib\request.py", line 163, in urlopen
  File "C:\Program Files\Python35\lib\urllib\request.py", line 466, in open
  File "C:\Program Files\Python35\lib\urllib\request.py", line 484, in _open
  File "C:\Program Files\Python35\lib\urllib\request.py", line 444, in _call_chain
  File "C:\Program Files\Python35\lib\urllib\request.py", line 1282, in http_open
  File "C:\Program Files\Python35\lib\urllib\request.py", line 1254, in do_open
  File "C:\Program Files\Python35\lib\http\client.py", line 1107, in request
  File "C:\Program Files\Python35\lib\http\client.py", line 1147, in _send_request
  File "C:\Program Files\Python35\lib\http\client.py", line 1084, in putheader
ValueError: Invalid header value b'AUTH=<script src="/gui/js/shared.js"></script>\n<head>\n    <title>Login | Access</title>\n\t<link rel="shortcut icon" type="image/png" href="/gui/img/favicon.png"/>\n\t<link rel="stylesheet" href="/gui/css/shared.css" type="text/css">\n\t<link rel="stylesheet" href="/gui/css/basic.css" type="text/css">\n\t<link rel="stylesheet" href="/gui/css/login.css" type="text/css">\n</head>\n<form action="/enter" method="POST">\n    <br><br><br><br>\n\t<div class="login">\n\t\t<div class="login-screen">\n\t\t\t<div class="app-title">\n\t\t\t\t<h3 style="color: black">Access</h3>\n\t\t\t</div>\n\t\t\t<div class="login-form">\n\t\t\t\t<div class="control-group">\n\t\t\t\t<input type="text" class="login-field" value="" placeholder="username" name="username">\n\t\t\t\t<label class="login-field-icon fui-user" for="login-name"></label>\n\t\t\t\t</div>\n\n\t\t\t\t<div class="control-group">\n\t\t\t\t<input type="password" class="login-field" value="" placeholder="password" name="password">\n\t\t\t\t<label class="login-field-icon fui-lock" for="login-pass"></label>\n\t\t\t\t</div>\n\n                <input type="submit" value="Log in" class="button-success" >\n\t\t\t    <br>\n                <p style="font-size:12px;color:grey">Trouble logging in?<br>Clear your cookies and try again.<br>For the best experience, use Chrome</p>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</form>\n<script>\n    document.cookie.split(";").forEach(function(c) { document.cookie = c.replace(/^ +/, "").replace(/=.*/, "=;expires=" + new Date().toUTCString() + ";path=/"); });\n</script>'
`

The POST request:
`
POST /login HTTP/1.1
Accept-Encoding: identity
Content-Type: application/json
Content-Length: 127
Host: 10.0.0.103:8888
User-Agent: Python-urllib/3.5
Connection: close

{"hostname": "xxx", "fqdn": "xxx.caldera.lab", "dns_domain": "caldera.lab", "windows_domain": "CALDERA", "agent": true}
`

The response:
`
Content-Type: text/html; charset=utf-8
Content-Length: 1459
Date: Tue, 09 Jul 2019 13:19:09 GMT
Server: Python/3.5 aiohttp/3.4.4
Connection: close

<script src="/gui/js/shared.js"></script>
..... etc ....
`

I have tried numerous clean installations but I always run into this issue with the latest Caldera version.

**Comment by mikeyijdskfhsd** [comment]
I think I fixed the issue for myself. It had to do with the order of the adversary plugin in the conf/local.yml. It needs to be before the gui plugin otherwise the login request isn't caught.

**Comment by amonyphily** [comment]
Fixed with this solution 
Thank you !!

**Comment by p57p57** [comment]
@mikeyijdskfhsd :  seems that your tip fixed the connection problem as well for us. We now see the agents in adversary. Thx a lot
Now we are trying to add several hosts (same domain) into a network. Seems it does'nt work. Step by step ...

**Comment by wietze** [comment]
I still think this should be fixed! I had the same issue and it took me quite some time to debug this issue.

The problem is that there are to routers for `/login`, one by the GUI and one by the Adversary plugin.
