### ISSUE TITLE
Dockerfile for 5.0.0 needs a small update to build the vue?

### ISSUE THREAD

**Issue by cln-io** [mitre/caldera#2889]
I'm trying to build a docker image for the 5.0.0 release

But I don't think the Dockerfile was updated to build the vue once.
It builds fine, but when running caldera in a docker after build it seems to be not liking it

```
2024-02-20 10:46:45 - WARNING (c_adversary.py:95 verify) Objective referenced in adversary ef4d997c-a0d1-4067-9efa-87c58682db71 but not found: c495a9828-cab1-44dd-a0ca-66e58177d8c. Setting default objective.
Traceback (most recent call last):
  File "/opt/venv/caldera/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 561, in __init__
    raise ValueError("Not a directory")
ValueError: Not a directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/app/server.py", line 260, in <module>
    run_tasks(services=app_svc.get_services(), run_vue_server=args.uiDevHost)
  File "/usr/src/app/server.py", line 78, in run_tasks
    loop.run_until_complete(RestApi(services).enable())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/src/app/app/api/rest_api.py", line 32, in enable
    self.app_svc.application.router.add_static('/assets', 'plugins/magma/dist/assets/', append_version=True)
  File "/opt/venv/caldera/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 1136, in add_static
    resource = StaticResource(
               ^^^^^^^^^^^^^^^
  File "/opt/venv/caldera/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 563, in __init__
    raise ValueError(f"No directory exists at '{directory}'") from error
ValueError: No directory exists at '/usr/src/app/plugins/magma/dist/assets'

```

Seeing if I can update it and PR it. 

Unless I'm in need for caffeine and I'm not understanding something here 🙊

**Comment by cln-io** [comment]
PR included, docker builds fine now, and caldera boots up as expected 🎉

**Comment by elegantmoose** [comment]
It does (need to be updated). We were allowing for a slight delay to make sure Magma was stable before updating the dockerfile. But I see you PR and it looks good. I will try to test it ASAP.

**Comment by cln-io** [comment]
I'm not sure its related but I'm running into 500's on /api/v2/health 
and the login page isn't shown or is unresponsive.

will investigate

**Comment by 3isenHeiM** [comment]
I've pulled the latest commit on the master (08c64d3efb1d8f10727456a3e2e95f476f92c96c), checked out the master branch and built with `docker-compose build`, but I still have the same error:

```
caldera_1  | 2024-03-13 08:52:02 INFO     Docs built successfully.                 hook.py:58
caldera_1  | Traceback (most recent call last):
caldera_1  |   File "/opt/venv/caldera/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 561, in __init__
caldera_1  |     raise ValueError("Not a directory")
caldera_1  | ValueError: Not a directory
caldera_1  | 
caldera_1  | The above exception was the direct cause of the following exception:
caldera_1  | 
caldera_1  | Traceback (most recent call last):
caldera_1  |   File "/usr/src/app/server.py", line 281, in <module>
caldera_1  |     run_tasks(services=app_svc.get_services(), run_vue_server=args.uiDevHost)
caldera_1  |   File "/usr/src/app/server.py", line 89, in run_tasks
caldera_1  |     loop.run_until_complete(RestApi(services).enable())
caldera_1  |   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
caldera_1  |     return future.result()
caldera_1  |            ^^^^^^^^^^^^^^^
caldera_1  |   File "/usr/src/app/app/api/rest_api.py", line 32, in enable
caldera_1  |     self.app_svc.application.router.add_static('/assets', 'plugins/magma/dist/assets/', append_version=True)
caldera_1  |   File "/opt/venv/caldera/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 1136, in add_static
caldera_1  |     resource = StaticResource(
caldera_1  |                ^^^^^^^^^^^^^^^
caldera_1  |   File "/opt/venv/caldera/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 563, in __init__
caldera_1  |     raise ValueError(f"No directory exists at '{directory}'") from error
caldera_1  | ValueError: No directory exists at '/usr/src/app/plugins/magma/dist/assets'
```
