### ISSUE TITLE
Error running server

### ISSUE THREAD

**Issue by Christopherhausner** [mitre/caldera#2892]
python3 server.py --insecure --build
I ran this^^^^
and the output is below. I have a M2 Max chip and I am running ARM Ubuntu on Vmware fusion.

2024-02-19 22:07:45 - WARNING (server.py:202 <module>) --insecure flag set. Caldera will use the default.yml config file.
2024-02-19 22:07:45 - INFO  (server.py:211 <module>) Using main config from conf/default.yml
2024-02-19 22:07:45 - INFO  (server.py:247 <module>) Building VueJS front-end.
Traceback (most recent call last):
  File "/home/chrishausner/caldera/server.py", line 248, in <module>
	subprocess.run(["npm", "install"], cwd="plugins/magma", check=True)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
	with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
	self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
	raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'npm'

**Comment by plue0709** [comment]
`sudo apt-get install npm`

**Comment by elegantmoose** [comment]
Please see README regarding system dependencies for v5.

Reopen if still having issues.
