### ISSUE TITLE
Can't save Settings for Agents

### ISSUE THREAD

**Issue by l1ghts4ber** [mitre/caldera#2907]
**Describe the bug**
I have deployed version 5.0.0 of caldera. Following the training plugin one task is to update an agent. When trying to update the settings of an deployed  agent the button "Save Settings" does not work. 

**To Reproduce**
1. Klick on deployed agent
2. Change Settings like Group or Sleep Timer
3. Klick on Save Settings

**Expected behavior**
The Agent Details window should be closed and the new settings should be saved. 

**Desktop (please complete the following information):**
 - OS: Kali VM version 6.5.0
 - Browser Safari 115.7.0esr (64-bit)
 - Caldera v5.0.0

**Comment by l1ghts4ber** [comment]
I was also able to reproduce the bug with a fresh caldera installation and the usage of Google Chrome Version 122.0.6261.111.

**Comment by aut0exec** [comment]
Same issue here using FireFox 115.8.0esr and Chrome 122.0.6261.94.

**Comment by dkorzhevin** [comment]
I can confirm issue in Chrome 122.0.6261.112 (Official Build) (x86_64) on MacOS 14.3.1 (23D60)

**Comment by elegantmoose** [comment]
@dkorzhevin @aut0exec @l1ghts4ber Anyone try it with Chrome on Ubuntu?

*Im not able to replicate it on that environment.

**Comment by jeyam93** [comment]
I tried a few minutes ago, doesn't work for me either.
Ubuntu 22.04.4 LTS
Google Chrome 122.0.6261.111

In the browser console I get the same two error message I get in Chrome under Windows 10:
`PATCH http://[Host-IP]:8888/api/v2/agents/xmivtk 422 (Unprocessable Entity)
`
```
Uncaught (in promise) Error: Request failed with status code 422
    at _$ (index.2ed6dbe1.js:9:9616)
    at mG (index.2ed6dbe1.js:9:9740)
    at XMLHttpRequest.v (index.2ed6dbe1.js:10:1820)
```

When I look at the request in the browser console, under payload everything looks fine, but under preview and response I see this:

```
{
  "json": {
    "pid": [
      "Unknown field."
    ],
    "privilege": [
      "Unknown field."
    ],
    "platform": [
      "Unknown field."
    ],
    "proxy_chain": [
      "Unknown field."
    ],
    "origin_link_id": [
      "Unknown field."
    ],
    "available_contacts": [
      "Unknown field."
    ],
    "upstream_dest": [
      "Unknown field."
    ],
    "proxy_receivers": [
      "Unknown field."
    ],
    "exe_name": [
      "Unknown field."
    ],
    "paw": [
      "Unknown field."
    ],
    "username": [
      "Unknown field."
    ],
    "ppid": [
      "Unknown field."
    ],
    "server": [
      "Unknown field."
    ],
    "deadman_enabled": [
      "Unknown field."
    ],
    "host": [
      "Unknown field."
    ],
    "location": [
      "Unknown field."
    ],
    "architecture": [
      "Unknown field."
    ],
    "contact": [
      "Unknown field."
    ],
    "host_ip_addrs": [
      "Unknown field."
    ],
    "executors": [
      "Unknown field."
    ]
  }
}
```

**Comment by younggod69** [comment]
Hello! I am encountering this issue too. While I was trying to debug it, I have encountered another bug. 
The sandcat agent is 100% alive and working but on "Agent Details" tab where the updates should be made (group, sleep time, etc) after 1 minute will appear as 'dead' only there.

As starting point for debug, I've found the following two functions:
- In _plugins/magma/src/stores/agentStore.js_ - useAgentStore-> actions -> **saveSelectedAgent()** (for initial bug)
- In _plugins/magma/src/components/operations/AgentDetailsModal.vue_ - **getAgentStatus()** (for my bug)

![00_agent_details_issue](https://github.com/mitre/caldera/assets/42208291/8ea05e58-d3ee-4a2e-8e02-920a36de83f2)

**Comment by l1ghts4ber** [comment]
I was able to reproduce on a fresh install on Ubuntu 22.04.4 LTS @ Google Chrome v123.0.6312.58.

**Comment by dkorzhevin** [comment]
@l1ghts4ber could you please provide your's steps to reproduce?

**Comment by l1ghts4ber** [comment]
> @l1ghts4ber could you please provide your's steps to reproduce?

I could not fix the bug but reproduce it with fresh Install on different OS and Browser. Sorry for the misunderstanding.

**Comment by elegantmoose** [comment]
@l1ghts4ber So, clarifying you pulled down the Master branch (not v 5.0.0) and were still having this error?

**Comment by l1ghts4ber** [comment]
Tried both pulling methods (--recursive and --recursive --branch 5.0.0) Error ist still the same. 
 
I watched the network traffic and everytime I try to save the setting get a 422 response.

![Screenshot 2024-04-04 063934](https://github.com/mitre/caldera/assets/127923841/82cbbc7c-e1e0-42eb-86bc-54b60570093a)

More screenshots of the request (sleep_min changed to 38):

![image](https://github.com/mitre/caldera/assets/127923841/409434e6-14e3-4785-ae0d-f1350e4420d7)

Response: 

![image](https://github.com/mitre/caldera/assets/127923841/120bfc66-2889-4724-bfc3-7b2f86a11029)

**Comment by elegantmoose** [comment]
I'm stumped. I cannot replicate, no how hard I try. (works fine for me, see video)

@clenk @JamieScottC Any ideas?
[Screencast from 04-07-2024 12:05:50 PM.webm](https://github.com/mitre/caldera/assets/7109639/8ba21247-0602-4f49-8105-1cede32b0553)

**Comment by dkorzhevin** [comment]
@elegantmoose Could you please try to change "sleep timer" Min and Max and try to save? I will try to reproduce with latest master on a fresh VM too.

**Comment by wilczekj** [comment]
I can confirm the same issue on :
- Chrome Version 123.0.6312.106 (Official Build) (64-bit)
- Edge Version 123.0.2420.81 (Official build) (64-bit)

**Comment by l1ghts4ber** [comment]
> I'm stumped. I cannot replicate, no how hard I try. (works fine for me, see video)
> 
> @clenk @JamieScottC Any ideas? [Screencast from 04-07-2024 12:05:50 PM.webm](https://github.com/mitre/caldera/assets/7109639/8ba21247-0602-4f49-8105-1cede32b0553)

Can you maybe provide your exact installation steps on a clean ubuntu vm? With the installation steps from the documentation I couldn't run the server build and had to do some workarounds. Maybe we have some differences here?

**Comment by elegantmoose** [comment]
Lol so I set up a screen recording and started installing from scratch, and I finally reproduced it. 

--> Now can look into.

**Comment by elegantmoose** [comment]
@Guil33 Correct. Im glad I looked at the issue board as I was about to fix.

Did you want to open a PR since you got it already?

**Comment by dkorzhevin** [comment]
Thank you for the fix.
