### ISSUE TITLE
Trying to start caldera with --build fails 

### ISSUE THREAD

**Issue by dougjpsantos1981** [mitre/caldera#2931]
ubuntu@ip-172-31-27-19:~/caldera$ python3 server.py --insecure --build
2024-03-27 20:14:12 WARNING  --insecure flag set. Caldera will use the default user accounts in default.yml config file.                                                                       server.py:216
                    INFO     Using main config from conf/default.yml                                                                                                                           server.py:225
2024-03-27 20:14:13 INFO     Building VueJS front-end.                                                                                                                                         server.py:261
Traceback (most recent call last):
  File "/home/ubuntu/caldera/server.py", line 262, in <module>
    subprocess.run(["npm", "install"], cwd="plugins/magma", check=True)
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'npm'

this is a 22.04 ubuntu fresht install from AWS.

**Comment by elegantmoose** [comment]
npm installed?

**Comment by elegantmoose** [comment]
@dougjpsantos1981 Any luck?

**Comment by elegantmoose** [comment]
reopen if still having trouble.
