### ISSUE TITLE
Docker image (ghcr.io/mitre/caldera:5.0.0) does not contain Magma (dist) build files

### ISSUE THREAD

**Issue by d3vzer0** [mitre/caldera#2949]
**Describe the bug**
The docker image (ghcr.io/mitre/caldera:5.0.0) does not contain the Magma plugin (dist) build files. Starting the container will fail with the following error: 

```
ValueError: No directory exists at '/usr/src/app/plugins/magma/dist/assets'
```

This could be caused by an older Dockerfile being used which does not build Magma plugin's Vue project as part of the docker build process. If I build the container myself using the lasted Dockerfile found in the repo, the container will start successfully.

**To Reproduce**
1. Start a caldera container with docker using `docker run ghcr.io/mitre/caldera:5.0.0` or
2. Start a calera container with Podman using `podman run ghcr.io/mitre/caldera:5.0.0`

**Expected behavior**
The container to start successfully

**Screenshots**
![Screenshot 2024-04-15 at 14 49 43](https://github.com/mitre/caldera/assets/34250156/d2389b6f-475c-40d1-abbf-7c9e8cb9c6f1)

**Desktop (please complete the following information):**
 - OS: Rocky Linux

**Comment by d3vzer0** [comment]
It seems that this issue is related but the changes are not represented in the hosted Docker image itself (yet): https://github.com/mitre/caldera/issues/2889.

**Comment by digoblin** [comment]
Hi there, I was having the same problem starting the docker-compose file and I identified the problem with the volume mount referenced in the docker-compose file, I created a workaround for those that want to use the caldera's git folder as the containers /usr/src/app folder:

The problem I identified is that the docker-compose file, uses the current dir, supposedly the caldera's git folder, as its app folder:
```
volumes:
      - ./:/usr/src/app
```

Now the problem with the latest build of the Docker file (https://github.com/mitre/caldera/commit/f9b0ed23ba77b7e48e98f03ae4560473d3eda298) is that it is using the **/usr/src/app** folder to install the magma plugin and when a new container is started with the volume mounted like in the docker-compose file, the contents of the plugins/magma/ folder get overridden with the default files of caldera's git folder.

My workaround was to create a ubuntu container with the caldera's github folder mounted inside it, run the instructions of the Dockerfile pertaining the magma plugin installation and thus achieve a permanent plugin installation.

First we create the fix file in the caldera's git folder, **fix.sh**:

```
#!/bin/sh
apt-get update && \
apt-get install -y nodejs npm && \
# Directly use npm to install dependencies and build the application
(cd plugins/magma && npm install) && \
(cd plugins/magma && npm run build) && \
# Remove Node.js, npm, and other unnecessary packages
apt-get remove -y nodejs npm && \
apt-get autoremove -y && \
apt-get clean && \
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

now save it and then give it execution permissions:
```
chmod +x fix.sh
```

now we create a temporary ubuntu docker container with the caldera folder mounted inside in **/app** path, and execute the **fix.sh** script:
```
docker run --rm -v $PWD:/app ubuntu:23.04 ./app/fix.sh
#    --rm - remove the container once it is done
#   -v mount the current directory ($PWD) in /app inside the container
```

now the files in **plugins/magma/dist** folder should be present and we can start the docker-compose project:
```
docker-compose up
```

**Comment by d3vzer0** [comment]
@digoblin Correct, the latest build solves the issue but the image hosted on the repository doesn't work. I guess the only thing required is running the pipeline again to build + publish a new image :)

**Comment by vishwaspai** [comment]
Facing the exact same issue on latest (commit: b5a9bcbdf852b696624b5ad81fa0f561005f62a1)
`aldera-1  | 2024-07-12 10:07:15 INFO     Docs built successfully.                 hook.py:58
caldera-1  | Traceback (most recent call last):
caldera-1  |   File "/opt/venv/caldera/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 561, in __init__
caldera-1  |     raise ValueError("Not a directory")
caldera-1  | ValueError: Not a directory
caldera-1  | 
caldera-1  | The above exception was the direct cause of the following exception:
caldera-1  | 
caldera-1  | Traceback (most recent call last):
caldera-1  |   File "/usr/src/app/server.py", line 298, in <module>
caldera-1  |     run_tasks(services=app_svc.get_services(), run_vue_server=args.uiDevHost)
caldera-1  |   File "/usr/src/app/server.py", line 92, in run_tasks
caldera-1  |     loop.run_until_complete(RestApi(services).enable())
caldera-1  |   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
caldera-1  |     return future.result()
caldera-1  |            ^^^^^^^^^^^^^^^
caldera-1  |   File "/usr/src/app/app/api/rest_api.py", line 32, in enable
caldera-1  |     self.app_svc.application.router.add_static('/assets', 'plugins/magma/dist/assets/', append_version=True)
caldera-1  |   File "/opt/venv/caldera/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 1136, in add_static
caldera-1  |     resource = StaticResource(
caldera-1  |                ^^^^^^^^^^^^^^^
caldera-1  |   File "/opt/venv/caldera/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 563, in __init__
caldera-1  |     raise ValueError(f"No directory exists at '{directory}'") from error
caldera-1  | ValueError: No directory exists at '/usr/src/app/plugins/magma/dist/assets'
`
