### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by xXxSpicyBoiiixXx** [mitre/caldera#2992]
During the installation process, when standing up the server I get the following error. Not sure if anyone has been having issues with this as well. I am on a Linux machine but unsure why the compiler is having issues.

[vite:vue] Failed to resolve vue/compiler-sfc.
@vitejs/plugin-vue requires vue (>=3.2.25) to be present in the dependency tree.
error during build:
Error: Failed to resolve vue/compiler-sfc.
@vitejs/plugin-vue requires vue (>=3.2.25) to be present in the dependency tree.
    at resolveCompiler (/home/mali/caldera/plugins/magma/node_modules/@vitejs/plugin-vue/dist/index.js:3955:11)
    at Object.buildStart (/home/mali/caldera/plugins/magma/node_modules/@vitejs/plugin-vue/dist/index.js:4686:46)
    at /home/mali/caldera/plugins/magma/node_modules/rollup/dist/shared/rollup.js:22834:37
    at async Promise.all (index 4)
    at async /home/mali/caldera/plugins/magma/node_modules/rollup/dist/shared/rollup.js:23622:13
    at async catchUnfinishedHookActions (/home/mali/caldera/plugins/magma/node_modules/rollup/dist/shared/rollup.js:23132:20)
    at async rollupInternal (/home/mali/caldera/plugins/magma/node_modules/rollup/dist/shared/rollup.js:23620:5)
    at async doBuild (/home/mali/caldera/plugins/magma/node_modules/vite/dist/node/chunks/dep-689425f3.js:41710:24)
    at async build (/home/mali/caldera/plugins/magma/node_modules/vite/dist/node/chunks/dep-689425f3.js:41552:16)
    at async CAC.<anonymous> (/home/mali/caldera/plugins/magma/node_modules/vite/dist/node/cli.js:738:9)

**Comment by xXxSpicyBoiiixXx** [comment]
This was an npm issue. If you need to the guide on a Linux machine follow these steps if yo have similar issues. 

# Ensure that Node.js and npm are installed and accessible from your path
node -v 
npm -v

# clear npm cache 
sudo npm cache clean -f 

# installing nvm 
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash

# adding nvm to current shell
source ~/.[Your Shell]

#LTS support version of node.js
nvm install --lts
nvm use --lts

# reinstall npm globally
npm install -g npm@latest 

That should fix any issue with npm and caldera during that process. Afterwards you should be able to access the server on your localhost!
