### ISSUE TITLE
Issue with Operation Graph Not Rendering

### ISSUE THREAD

**Issue by HMAckerman** [mitre/caldera#3024]
**Describe the bug**
When navigating to Campaigns -> Operations and selecting an operation as either the red or the blue user, the operation graph fails to render, and an error message pops up. The error message in the console is the following:

**When I first browse to the page:**
`TypeError: Cannot read properties of undefined (reading 'paw')
    at index.95703d3b.js:115:36199`

The code block at the above line is the following:
```
At(async()=>{
            await i.getAgents(n),
            i.agents.length > 0 && g ? (h.agent = i.agents[0],
            h.executor = h.agent.executors[0]) : (h.agent = r.agent.paw, **this line
            h.executor = h.agent.executors[0]),
            await o.getAbilities(n),
            await s.getSources(n),
            await a.getFacts(n)
        }
```
**When I select an operation:**
I get screenshot 2 and the following error in the console:
`GET https://localhost.com:8443/api/v2/operations/summary 500 (Internal Server Error)  index.95703d3b.js:10`

The code block at the above line is the following:
```
e.cancelToken && e.cancelToken.subscribe(l),
        e.signal && (e.signal.aborted ? l() : e.signal.addEventListener("abort", l))),
        i || (i = null),
        c.send(i) **this line
```
**Additionally, I receive this**:
```
Error: Request failed with status code 500 index.95703d3b.js:112
    at w$ (index.95703d3b.js:9:9616)
    at bG (index.95703d3b.js:9:9740)
    at XMLHttpRequest.v (index.95703d3b.js:10:1820)
```
Line-by-line, the code blocks are the following:
***Line 1:***
`at w$ (index.95703d3b.js:9:9616)`
```
  , yG = _$
  , w$ = function(e, r, n, a, i) {
    var o = new Error(e); **this line
    return yG(o, r, n, a, i)
```
***Line 2:***
`at bG (index.95703d3b.js:9:9740)`
```
, _G = w$
  , bG = function(e, r, n) {
    var a = n.config.validateStatus;
    !n.status || !a || a(n.status) ? e(n) : r(_G("Request failed with status code " + n.status, n.config, null, n.request, n)) **this line
```
***Line 3:***
`at XMLHttpRequest.v (index.95703d3b.js:10:1820)`
```
        var h = LG(e.baseURL, e.url);
        c.open(e.method.toUpperCase(), IG(h, e.params, e.paramsSerializer), !0),
        c.timeout = e.timeout;
        function v() {
            if (!!c) {
                var g = "getAllResponseHeaders"in c ? $G(c.getAllResponseHeaders()) : null
                  , m = !s || s === "text" || s === "json" ? c.responseText : c.response
                  , y = {
                    data: m,
                    status: c.status,
                    statusText: c.statusText,
                    headers: g,
                    config: e,
                    request: c
                };
               PG(function(w){ **this line
                    n(w),
                    u()
                }, function(w) {
                    a(w),
                    u()
                }, y),
                c = null
            }
```
**To Reproduce**
1. Log in as either red or blue.
2. Navigate to Campaigns.
3. Navigate to Operations.
4. This is where the TypeError occurs.
5. Select an Operation.
6. Operation fails to render, and the error message pops up. This is where the 500 (Internal Server Error) occurs.

**Expected behavior**
Expected behavior is the selected Operations graph renders and displays something similar to screenshot 1 below (this is an old screenshot pulled from the documentation about lateral movement but should hopefully make sense on what I'm talking about).

**Screenshots**
Screenshot 1:
![image](https://github.com/user-attachments/assets/1856e65f-9aaa-45b4-811c-7c6e4cd3f79c)

The error message I get in question looks like this (referenced as screenshot 2):
<img width="602" alt="image" src="https://github.com/user-attachments/assets/ae438d44-e44a-4faa-8c07-5c5423ce50f5">

**Desktop (please complete the following information):**
 - Caldera Host OS: Ubuntu 22.04
 - OS: Windows 11
 - Browser: Edge
 - Version: 126.0.2592.113 (Official build) (64-bit)

**Additional context**
This is my first ever Github issue I've opened, so I apologize if I have not followed proper procedure, didn't add enough information, or added too much information. This Caldera instance is from the latest master branch. Please let me know if any more information is required, or if I need to separate anything out into another issue for easier tracking purposes.

**Comment by elegantmoose** [comment]
So you run an operation first successfully, and then try to navigate back to it later and it errors?

**Comment by HMAckerman** [comment]
> So you run an operation first successfully, and then try to navigate back to it later and it errors?

That is correct. However, I did discover a pretty reliable way to reproduce the issue. As a note, the graph does NOT error when you still have an agent running. 
<img width="830" alt="image" src="https://github.com/user-attachments/assets/5587917b-1b57-49d5-8364-90d00ce66450">

However, when I kill the agent and delete it from the agent list, the operation then errors out. 

Here is where the agent is dead and untrusted, and the operation does not error out:
<img width="832" alt="image" src="https://github.com/user-attachments/assets/b3646a07-5fde-4594-ac4f-845e30e8dbe3">
<img width="830" alt="image" src="https://github.com/user-attachments/assets/6a017a98-f3a6-4518-8c43-f0fc612aa2f0">


As soon as I remove the agent, this happens:

<img width="836" alt="image" src="https://github.com/user-attachments/assets/5ccd9cf6-0961-4304-93fc-f5d04f9518c7">
<img width="838" alt="image" src="https://github.com/user-attachments/assets/16b53e6d-f937-4f9e-86d4-3c9dcc38545a">


The errors in the console are the same as posted above in my initial comment.

**Comment by Anthem-whisper** [comment]
same problem.
![image](https://github.com/user-attachments/assets/327996f0-76be-4fd0-8b8d-762379fe9073)

**Comment by blinkomaniak** [comment]
Hello, I have deployed Caldera in Kali Rolling and Have the same issues with the graph data rendering. But I can run Kali smoothly. I have enabled the --debug flag when starting Caldera but I haven't spotted logs regarding this issue. Please, Any recommendation?

**Comment by deacon-mp** [comment]
This issue has been migrated to the Magma plugin repository where it belongs: mitre/magma#89
