### ISSUE TITLE
Error Running after following the install process in documentation

### ISSUE THREAD

**Issue by Sup34MaNIaM** [mitre/caldera#3034]
I am getting the following error when running on Ubuntu 24.04 after following the directions and troubleshooting the requirements install:  

FileNotFoundError: [Errno 2] No such file or directory: 'plugins/magma/dist'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/caldera/server.py", line 260, in <module>
    run_tasks(services=app_svc.get_services(), run_vue_server=args.uiDevHost)
  File "/home/ubuntu/caldera/server.py", line 78, in run_tasks
    loop.run_until_complete(RestApi(services).enable())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/caldera/app/api/rest_api.py", line 32, in enable
    self.app_svc.application.router.add_static('/assets', 'plugins/magma/dist/assets/', append_version=True)
  File "/home/ubuntu/.local/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py", line 1206, in add_static
    resource = StaticResource(
               ^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py", line 569, in __init__
    raise ValueError(f"'{directory}' does not exist") from error
ValueError: 'plugins/magma/dist/assets/' does not exist

Can you please assist.

**Comment by elegantmoose** [comment]
what commands did you run?

Did you use the '--build' flag when starting the server the first time?

**Comment by deacon-mp** [comment]
Thank you for the report\! This appears to be an environment/setup issue rather than a core Caldera bug. For help with installation and setup, please see the [Caldera documentation](https://caldera.readthedocs.io/) or open a discussion. Closing as this doesn't appear to be a reproducible core Caldera bug — feel free to reopen if you can provide more details about your environment and the specific error.
