### ISSUE TITLE
i can't run the Caldera server

### ISSUE THREAD

**Issue by AshSecThor** [mitre/caldera#3051]
**after starting the command** 
┌──(kali㉿kali)-[~/caldera]
└─$ python3 server.py --insecure --build
**i've get this warning message** 

2024-09-17 08:44:26 WARNING  --insecure flag set. Caldera will use the default user accounts in default.yml config file.                             server.py:226
                    INFO     Using main config from conf/default.yml                                                                                 server.py:235
2024-09-17 08:44:27 INFO     Setting VueJS environment file.                                                                                         server.py:151
                    INFO     Building VueJS front-end.                                                                                               server.py:273
Traceback (most recent call last):
  File "/home/kali/caldera/server.py", line 274, in <module>
    subprocess.run(["npm", "install"], cwd=MAGMA_PATH, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'npm'

![Capture d'écran 2024-09-17 085756](https://github.com/user-attachments/assets/9f45af10-3b6a-4cc3-ac88-fa2a4aa5e15c)

**Comment by lpinder** [comment]
also getting this error.

**Comment by AshSecThor** [comment]
I found the solution by installing nodejs using : sudo apt-get install nodejs npm

**Comment by lpinder** [comment]
YES! thank you!
