### ISSUE TITLE
Not able to run Caldera in Kali Linux

### ISSUE THREAD

**Issue by farhadanwari** [mitre/caldera#3056]
I am facing an issue with Caldera and am not able to run it on my Kali Linux machine at all. 

I tried running Caldera in my Kali Linux machine but unfortunately, it's showing an error while running the server using the `python3 server.py --insecure --build`
I thought maybe it was because I did not install all the required libraries and packages, however even after installing all the requirements using the `pip3 install -r requirements` it did not work. I tried installing npm separately using `sudo apt install npm` and it was successfully installed. However, when I tried to run the server.py, it showed a different error. 
Here is the error output that I got: 
INFO     Invalid Github Gist personal API token provided. Gist C2 contact will not be started.                                                          contact_gist.py:70
Traceback (most recent call last):
  File "/home/cypher/caldera/server.py", line 298, in <module>
    run_tasks(services=app_svc.get_services(), run_vue_server=args.uiDevHost)
  File "/home/cypher/caldera/server.py", line 80, in run_tasks
    loop.run_until_complete(app_svc.register_contacts())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/cypher/caldera/app/service/app_svc.py", line 150, in register_contacts
    await self.register_contact_tunnels(contact_svc)
  File "/home/cypher/caldera/app/service/app_svc.py", line 155, in register_contact_tunnels
    tunnel_class = import_module(tunnel_module_name).Tunnel
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/cypher/caldera/app/contacts/tunnels/tunnel_ssh.py", line 3, in <module>
    import asyncssh
  File "/home/cypher/.local/lib/python3.11/site-packages/asyncssh/__init__.py", line 31, in <module>
    from .agent import SSHAgentClient, SSHAgentKeyPair, connect_agent
  File "/home/cypher/.local/lib/python3.11/site-packages/asyncssh/agent.py", line 34, in <module>
    from .public_key import KeyPairListArg, SSHCertificate, SSHKeyPair
  File "/home/cypher/.local/lib/python3.11/site-packages/asyncssh/public_key.py", line 35, in <module>
    from .crypto import ed25519_available, ed448_available
  File "/home/cypher/.local/lib/python3.11/site-packages/asyncssh/crypto/__init__.py", line 58, in <module>
    from .x509 import X509Certificate, X509Name, X509NamePattern
  File "/home/cypher/.local/lib/python3.11/site-packages/asyncssh/crypto/x509.py", line 32, in <module>
    from OpenSSL import crypto
  File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import SSL, crypto
  File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 19, in <module>
    from OpenSSL.crypto import (
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1616, in <module>
    class X509StoreFlags:
  File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1635, in X509StoreFlags
    NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?

I tried it with my friends' PCs but they had different problems when trying to login into the Caldera dashboard by entering the username and password, it shows an error below the password field as "Not Found....". and it doesn't allow me to log in at all and keeps bringing the login page.

How to fix this? Do I need to change any configurations or install anything else?
![image](https://github.com/user-attachments/assets/66b205fc-4bff-4a5c-ae7d-129e7c747fb8)
![image](https://github.com/user-attachments/assets/0d10163a-403e-4713-ba72-9662c05cfab6)
![image](https://github.com/user-attachments/assets/a9dffa77-85e7-4e05-9c96-643b295c188a)
![image](https://github.com/user-attachments/assets/a4e09fca-46ab-4760-b6fa-1eeb6363de57)
![image](https://github.com/user-attachments/assets/9a859ef5-805d-4534-b06e-34064bc7896a)

**Comment by farhadanwari** [comment]
> I am facing an issue with Caldera and am not able to run it on my Kali Linux machine at all.
> 
> I tried running Caldera in my Kali Linux machine but unfortunately, it's showing an error while running the server using the `python3 server.py --insecure --build` I thought maybe it was because I did not install all the required libraries and packages, however even after installing all the requirements using the `pip3 install -r requirements` it did not work. I tried installing npm separately using `sudo apt install npm` and it was successfully installed. However, when I tried to run the server.py, it showed a different error.
> 
> Here is the error output that I got:
> 
> ```
> INFO     Invalid Github Gist personal API token provided. Gist C2 contact will not be started.                                                          contact_gist.py:70
> Traceback (most recent call last):
>   File "/home/cypher/caldera/server.py", line 298, in <module>
>     run_tasks(services=app_svc.get_services(), run_vue_server=args.uiDevHost)
>   File "/home/cypher/caldera/server.py", line 80, in run_tasks
>     loop.run_until_complete(app_svc.register_contacts())
>   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
>   File "/home/cypher/caldera/app/service/app_svc.py", line 150, in register_contacts
>     await self.register_contact_tunnels(contact_svc)
>   File "/home/cypher/caldera/app/service/app_svc.py", line 155, in register_contact_tunnels
>     tunnel_class = import_module(tunnel_module_name).Tunnel
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
>   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>   File "/home/cypher/caldera/app/contacts/tunnels/tunnel_ssh.py", line 3, in <module>
>     import asyncssh
>   File "/home/cypher/.local/lib/python3.11/site-packages/asyncssh/__init__.py", line 31, in <module>
>     from .agent import SSHAgentClient, SSHAgentKeyPair, connect_agent
>   File "/home/cypher/.local/lib/python3.11/site-packages/asyncssh/agent.py", line 34, in <module>
>     from .public_key import KeyPairListArg, SSHCertificate, SSHKeyPair
>   File "/home/cypher/.local/lib/python3.11/site-packages/asyncssh/public_key.py", line 35, in <module>
>     from .crypto import ed25519_available, ed448_available
>   File "/home/cypher/.local/lib/python3.11/site-packages/asyncssh/crypto/__init__.py", line 58, in <module>
>     from .x509 import X509Certificate, X509Name, X509NamePattern
>   File "/home/cypher/.local/lib/python3.11/site-packages/asyncssh/crypto/x509.py", line 32, in <module>
>     from OpenSSL import crypto
>   File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
>     from OpenSSL import SSL, crypto
>   File "/usr/lib/python3/dist-packages/OpenSSL/SSL.py", line 19, in <module>
>     from OpenSSL.crypto import (
>   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1616, in <module>
>     class X509StoreFlags:
>   File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1635, in X509StoreFlags
>     NOTIFY_POLICY: int = _lib.X509_V_FLAG_NOTIFY_POLICY
>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'. Did you mean: 'X509_V_FLAG_EXPLICIT_POLICY'?
> ```
> 
> I tried it with my friends' PCs but they had different problems when trying to login into the Caldera dashboard by entering the username and password, it shows an error below the password field as "Not Found....". and it doesn't allow me to log in at all and keeps bringing the login page.
> 
> How to fix this? Do I need to change any configurations or install anything else? ![image](https://private-user-images.githubusercontent.com/59016488/370123202-66b205fc-4bff-4a5c-ae7d-129e7c747fb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjEwOTMsIm5iZiI6MTcyNzE2MDc5MywicGF0aCI6Ii81OTAxNjQ4OC8zNzAxMjMyMDItNjZiMjA1ZmMtNGJmZi00YTVjLWFlN2QtMTI5ZTdjNzQ3ZmI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA2NTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM2Nzg2NDg5Mjk4NmU0MTAzZWNhMjVkNGM2YmFiYzcxM2UwYWQ2NGM2MjBmNzhiNDkyNDM1NzQxY2U3NGNkYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WYL-ubMgjvPiRYy4xLfuvYDv_DgZsNCv1pmeq0RDGMg) ![image](https://private-user-images.githubusercontent.com/59016488/370123296-0d10163a-403e-4713-ba72-9662c05cfab6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjEwOTMsIm5iZiI6MTcyNzE2MDc5MywicGF0aCI6Ii81OTAxNjQ4OC8zNzAxMjMyOTYtMGQxMDE2M2EtNDAzZS00NzEzLWJhNzItOTY2MmMwNWNmYWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA2NTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjMmI0ZGNlYjdhYWUzZmUwMzVjYTg1YzcxZWYwNWY5NjhlY2M1YThmOTg3NjA4ZDgwNDA4YjNhOWJkMDYzODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jIswuPkpkIC732Kt538EXH3lG7lLoSG5I0oHu-gMPfg) ![image](https://private-user-images.githubusercontent.com/59016488/370123363-a9dffa77-85e7-4e05-9c96-643b295c188a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjEwOTMsIm5iZiI6MTcyNzE2MDc5MywicGF0aCI6Ii81OTAxNjQ4OC8zNzAxMjMzNjMtYTlkZmZhNzctODVlNy00ZTA1LTljOTYtNjQzYjI5NWMxODhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA2NTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmMTk2YjU2NDMzMjkxODZiODNiMzYwYmY5YmE0YjQ0ZjA4ZTc2NmY5YjY0ZWU1MTM4Yjc2MjJjOGU3ZDcwODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0N1pcQcFU-Q5kmJT1IldiG1hu2B9PYTnaDsFHyu0Krk) ![image](https://private-user-images.githubusercontent.com/59016488/370123416-a4e09fca-46ab-4760-b6fa-1eeb6363de57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjEwOTMsIm5iZiI6MTcyNzE2MDc5MywicGF0aCI6Ii81OTAxNjQ4OC8zNzAxMjM0MTYtYTRlMDlmY2EtNDZhYi00NzYwLWI2ZmEtMWVlYjYzNjNkZTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA2NTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjZjAwODBlYmRjN2JjOGZhYTRiNDU5ZjFiNjkwY2RjZWU0Mjg1MzY4ZmY1MzgzYTZiNTBiMzAwMzE4NmNhZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QBtc9p8dd7xTUVjgmBTHdQ1pW_YnP6RIB-r6yYysaVY) ![image](https://private-user-images.githubusercontent.com/59016488/370123456-9a859ef5-805d-4534-b06e-34064bc7896a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxNjEwOTMsIm5iZiI6MTcyNzE2MDc5MywicGF0aCI6Ii81OTAxNjQ4OC8zNzAxMjM0NTYtOWE4NTllZjUtODA1ZC00NTM0LWIwNmUtMzQwNjRiYzc4OTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI0VDA2NTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZDVhNjE0YjIxYWJhYzUyMmY5YjgyZGY5Njk3ZWE0ZWQ0ZjA5NzI2MTgxMGM3MDRhMWNjZTJlZTZlNmEzODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.24vNvJqNLFixOshhEZIt0sSHS-oRJcaDsZggzjPmRC8)

I have updated my Kali Linux again and now its version is 2023.3. I tried reinstalling the requirements.txt again but now it's showing a different error as shown below:
![image](https://github.com/user-attachments/assets/e3ce3164-af45-44b2-8849-db2ada148a96)
Even though it shows that the "aiohttp_apispec" is successfully downloaded and installed it still shows the following error while executing the server.py:
![image](https://github.com/user-attachments/assets/a5a6a801-db06-4db0-827d-0797b3a55646)

**Comment by farhadanwari** [comment]
Today I tried to install the requirements again by running `pip3 install -r requirements.txt` however I got the following error at the end: 
![image](https://github.com/user-attachments/assets/6409590d-87c1-440b-a3f2-d2872cf172f7)

**Comment by uruwhy** [comment]
In this case you'll want to set up a virtual Python environment to allow different pip requirement contexts. 

You can reference the [Python documentation for virtual environments](https://docs.python.org/3/library/venv.html) as needed, but the gist of it will look something like the following:
```bash
# create new virtual environment
python -m venv path/to/new/virtual/environment

# activate your virtual environment
source <venv>/bin/activate

# Install your dependencies
pip3 install -r requirements.txt
```

**Comment by farhadanwari** [comment]
> In this case you'll want to set up a virtual Python environment to allow different pip requirement contexts.
> 
> You can reference the [Python documentation for virtual environments](https://docs.python.org/3/library/venv.html) as needed, but the gist of it will look something like the following:
> 
> ```shell
> # create new virtual environment
> python -m venv path/to/new/virtual/environment
> 
> # activate your virtual environment
> source <venv>/bin/activate
> 
> # Install your dependencies
> pip3 install -r requirements.txt
> ```

I have followed your instructions and unfortunately, I am getting a new type of error while opening Caldera in my browser.

Here are the steps I followed: 
1. Created a Python virtual env
![image](https://github.com/user-attachments/assets/4d3a9cac-3cd6-44b0-8b23-796d34d2234e)
2. Activated the env
![image](https://github.com/user-attachments/assets/6f51672e-2a02-465c-a390-967056f3f3db)
3. Installed all the requirements using pip successfully 
![image](https://github.com/user-attachments/assets/2dcd6aad-8a80-43ea-a59f-22b6e303b85e)
![image](https://github.com/user-attachments/assets/b14ebf62-fc1e-41ee-ae39-1b6d2ba5e722)
4. rerun the server.py as shown below:
![image](https://github.com/user-attachments/assets/be7b01a9-089a-4477-80f0-4b79dc4b048b)
![image](https://github.com/user-attachments/assets/b0c1cd8b-dba6-43a8-a6fd-80f75e7aa335)
5. However, when I try to open the dashboard in my browser I get the "500 Internal Server Error" error message:
![image](https://github.com/user-attachments/assets/d88534b2-2538-4571-b0b7-5df2fc2607d2)

Note: I tried using 0.0.0.0:8888, 127.0.0.1:8888, and PRIVATE_IP:8888, but none worked.

What could be the issue and how to fix this?

**Comment by uruwhy** [comment]
This should be fixed in https://github.com/mitre/caldera/pull/3063, try pulling from main and seeing if it works then

**Comment by deacon-mp** [comment]
Thank you for the report\! This appears to be an environment-specific issue related to running Caldera on Kali Linux. For help with installation on different Linux distributions, please see the [Caldera documentation](https://caldera.readthedocs.io/) or open a discussion. Closing as this doesn't appear to be a reproducible core Caldera bug — feel free to reopen if you can provide more details about the specific errors encountered.
