### ISSUE TITLE
Got error while deploy with docker-compose after update to 5.0.0

### ISSUE THREAD

**Issue by dickens88** [mitre/caldera#3090]
**Describe the bug**
Hi , i cloned the project with command `git clone https://github.com/mitre/caldera.git --recursive` , and i'm sure the `magma` have been downloaded in the plugins folder. But when i try to deploy with docker-compose, it got this error.

```
caldera-1  | Traceback (most recent call last):
caldera-1  |   File "/opt/venv/caldera/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 561, in __init__
caldera-1  |     raise ValueError("Not a directory")
caldera-1  | ValueError: Not a directory
caldera-1  | 
caldera-1  | The above exception was the direct cause of the following exception:
caldera-1  | 
caldera-1  | Traceback (most recent call last):
caldera-1  |   File "/usr/src/app/server.py", line 260, in <module>
caldera-1  |     run_tasks(services=app_svc.get_services(), run_vue_server=args.uiDevHost)
caldera-1  |   File "/usr/src/app/server.py", line 78, in run_tasks
caldera-1  |     loop.run_until_complete(RestApi(services).enable())
caldera-1  |   File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
caldera-1  |     return future.result()
caldera-1  |            ^^^^^^^^^^^^^^^
caldera-1  |   File "/usr/src/app/app/api/rest_api.py", line 32, in enable
caldera-1  |     self.app_svc.application.router.add_static('/assets', 'plugins/magma/dist/assets/', append_version=True)
caldera-1  |   File "/opt/venv/caldera/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 1136, in add_static
caldera-1  |     resource = StaticResource(
caldera-1  |                ^^^^^^^^^^^^^^^
caldera-1  |   File "/opt/venv/caldera/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 563, in __init__
caldera-1  |     raise ValueError(f"No directory exists at '{directory}'") from error
caldera-1  | ValueError: No directory exists at '/usr/src/app/plugins/magma/dist/assets'
caldera-1 exited with code 1
```

**Comment by individual10121** [comment]
I ran into a similar issue.  I had to go into the magma directory and run the following:
`npm install
npm run build`

Then I was able to get it to launch.  But now I have an issue where no OS is listed in the deploy agents menu

**Comment by quentains** [comment]
I've tried to install Caldera using Docker this morning, version `5.3.0`. I have the exact same issue as the author of this issue. The plugin is correctly downloaded thanks to the recursive git pull. However, the `dist` folder is not created inside the container.

After the build process : 

```bash
docker compose run --rm --entrypoint /bin/bash caldera 

root@bb277cd981fa:/usr/src/app# ls-alh plugins/magma/
total 444K
drwxr-x---  6 root 2501 4.0K Aug 11 12:49 .
drwxr-x--- 18 root 2501 4.0K Aug 11 12:45 ..
-rw-r-----  1 root 2501   20 Aug 11 12:45 .dockerignore
-rw-r-----  1 root 2501   61 Aug 11 12:45 .eslintignore
-rw-r-----  1 root 2501  474 Aug 11 12:45 .eslintrc.js
-rw-r-----  1 root 2501   41 Aug 11 12:45 .git
drwxr-x---  3 root 2501 4.0K Aug 11 12:45 .github
-rw-r-----  1 root 2501  152 Aug 11 12:45 .gitignore
-rw-r-----  1 root 2501  12K Aug 11 12:45 LICENSE
-rw-r-----  1 root 2501 1.7K Aug 11 12:45 README.md
drwxr-xr-x  2 root root 4.0K Aug 11 12:49 __pycache__
drwxr-x---  3 root 2501 4.0K Aug 11 12:49 app
-rw-r-----  1 root 2501   40 Aug 11 12:45 babel.config.json
-rw-r-----  1 root 2501  346 Aug 11 12:45 hook.py
-rw-r-----  1 root 2501  369 Aug 11 12:45 index.html
-rw-r-----  1 root 2501  323 Aug 11 12:45 jest.config.js
-rw-r-----  1 root 2501   29 Aug 11 12:45 jsconfig.json
-rw-r-----  1 root 2501 351K Aug 11 12:45 package-lock.json
-rw-r-----  1 root 2501 2.1K Aug 11 12:45 package.json
-rw-r-----  1 root 2501  594 Aug 11 12:45 prebundle.js
drwxr-x---  9 root 2501 4.0K Aug 11 12:45 src
-rw-r-----  1 root 2501  439 Aug 11 12:45 vite.config.js
```

**Comment by quentains** [comment]
Just found out the issue is coming from the volume : https://github.com/mitre/caldera/blob/032ec16c60d650245e81ba0c7a9b1a000dbefb22/docker-compose.yml#L21-L22

This volume is required for the build process, but should be removed for the deployment.

One quick solution would be to propose two docker-compose.yml files. One for build phase, one for run phase.

**Comment by deacon-mp** [comment]
Thank you for the report\! This appears to be a Docker Compose environment issue after the 5.0.0 update. For help with Docker deployment and migration, please see the [Caldera documentation](https://caldera.readthedocs.io/) or open a discussion. Closing as this doesn't appear to be a reproducible core Caldera bug — feel free to reopen if you can provide specific error output and Docker version details.
