### ISSUE TITLE
TraceBack

### ISSUE THREAD

**Issue by Peppy9** [mitre/caldera#34]
Hello,
 
When I try to run caldera with pyhton3 I got this : 

DEBUG:app.server:Planner has started 
Process Process-1: 
Traceback (most recent call last): 
File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap 
self.run() 
File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run 
self._target(*self._args, **self._kwargs) 
File "/usr/local/bin/caldera/caldera/app/server.py", line 165, in sigint_handler 
target() 
File "/usr/local/bin/caldera/caldera/app/server.py", line 295, in planner_process 
rebuild_mappings = AttackTechnique.objects.count() == 0 
File "/home/hunter/.local/lib/python3.6/site-packages/mongoengine/queryset/manager.py", line 37, in __get__ 
queryset = queryset_class(owner, owner._get_collection()) 
File "/home/hunter/.local/lib/python3.6/site-packages/mongoengine/document.py", line 197, in _get_collection 
cls.ensure_indexes() 
File "/home/hunter/.local/lib/python3.6/site-packages/mongoengine/document.py", line 877, in ensure_indexes 
collection.create_index(fields, background=background, **opts) 
File "/home/hunter/.local/lib/python3.6/site-packages/pymongo/collection.py", line 1571, in create_index 
self.__create_index(keys, kwargs) 
File "/home/hunter/.local/lib/python3.6/site-packages/pymongo/collection.py", line 1459, in __create_index 
with self._socket_for_writes() as sock_info: 
File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__ 
return next(self.gen) 
File "/home/hunter/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 868, in _get_socket 
server = self._get_topology().select_server(selector) 
File "/home/hunter/.local/lib/python3.6/site-packages/pymongo/topology.py", line 214, in select_server 
address)) 
File "/home/hunter/.local/lib/python3.6/site-packages/pymongo/topology.py", line 189, in select_servers 
self._error_message(selector)) 
pymongo.errors.ServerSelectionTimeoutError: No replica set members available for replica set name "caldera" 
ERROR:app.server:No replica set members available for replica set name "caldera" 
Traceback (most recent call last): 
File "/usr/local/bin/caldera/caldera/app/server.py", line 124, in run 
web_process(settings, debug) 
File "/usr/local/bin/caldera/caldera/app/server.py", line 229, in web_process 
if Setting.objects.count() < 1: 
File "/home/hunter/.local/lib/python3.6/site-packages/mongoengine/queryset/queryset.py", line 133, in count 
return super(QuerySet, self).count(with_limit_and_skip) 
File "/home/hunter/.local/lib/python3.6/site-packages/mongoengine/queryset/base.py", line 389, in count 
return self._cursor.count(with_limit_and_skip=with_limit_and_skip) 
File "/home/hunter/.local/lib/python3.6/site-packages/pymongo/cursor.py", line 727, in count 
return self.__collection._count(cmd, self.__collation) 
File "/home/hunter/.local/lib/python3.6/site-packages/pymongo/collection.py", line 1344, in _count 
with self._socket_for_reads() as (sock_info, slave_ok): 
File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__ 
return next(self.gen) 
File "/home/hunter/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 904, in _socket_for_reads 
with self._get_socket(read_preference) as sock_info: 
File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__ 
return next(self.gen) 
File "/home/hunter/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 868, in _get_socket 
server = self._get_topology().select_server(selector) 
File "/home/hunter/.local/lib/python3.6/site-packages/pymongo/topology.py", line 214, in select_server 
address)) 
File "/home/hunter/.local/lib/python3.6/site-packages/pymongo/topology.py", line 189, in select_servers 
self._error_message(selector)) 
pymongo.errors.ServerSelectionTimeoutError: No replica set members available for replica set name "caldera" 

Someone know how to fix that ?

**Comment by gdraperi** [comment]
On my side I fixed this issue in the mongodb conf file by setting the property replSet = caldera.
