### ISSUE TITLE
Agent out of memory

### ISSUE THREAD

**Issue by scottma** [mitre/caldera#362]
Have anyone seen this? In the middle of a bunch of tests, it dies with an out of memory allocation. It looks like trying to allocate 17Gb of memory, which is strange.

runtime: VirtualAlloc of 17179869184 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw(0x6e6aa1, 0xd)
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/panic.go:617 +0x79
runtime.sysMap(0xc400400000, 0x400000000, 0x9365b8)
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/mem_windows.go:122 +0x138
runtime.(*mheap).sysAlloc(0x91db80, 0x400000000, 0x91db90, 0x200000)
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/malloc.go:633 +0x1d4
runtime.(*mheap).grow(0x91db80, 0x200000, 0x0)
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/mheap.go:1222 +0x49
runtime.(*mheap).allocSpanLocked(0x91db80, 0x200000, 0x9365c8, 0x289fe00)
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/mheap.go:1150 +0x3a9
runtime.(*mheap).alloc_m(0x91db80, 0x200000, 0x2890101, 0x289fe30)
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/mheap.go:977 +0xd0
runtime.(*mheap).alloc.func1()
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/mheap.go:1048 +0x53
runtime.(*mheap).alloc(0x91db80, 0x200000, 0x10101, 0xc00001a500)
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/mheap.go:1047 +0x91
runtime.largeAlloc(0x3fffffe00, 0xc000010101, 0xc00003f800)
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/malloc.go:1055 +0xa0
runtime.mallocgc.func1()
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/malloc.go:950 +0x4d
runtime.systemstack(0x0)
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/asm_amd64.s:351 +0x6b
runtime.mstart()
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/proc.go:1153

goroutine 65 [running]:
runtime.systemstack_switch()
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/asm_amd64.s:311 fp=0xc000157cf0 sp=0xc000157ce8 pc=0x455ba0
runtime.mallocgc(0x3fffffe00, 0x680a40, 0x1, 0xc000157dc8)
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/malloc.go:949 +0x8b1 fp=0xc000157d90 sp=0xc000157cf0 pc=0x40be61
runtime.makeslice(0x680a40, 0x3fffffe00, 0x3fffffe00, 0xc4003ffbf2)
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/slice.go:49 +0x73 fp=0xc000157dc0 sp=0xc000157d90 pc=0x440bb3
bytes.makeSlice(0x3fffffe00, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.5/libexec/src/bytes/buffer.go:232 +0x74 fp=0xc000157df0 sp=0xc000157dc0 pc=0x4d8e74
bytes.(*Buffer).grow(0xc000240300, 0x200, 0x20e)
        /usr/local/Cellar/go/1.12.5/libexec/src/bytes/buffer.go:145 +0x176 fp=0xc000157e40 sp=0xc000157df0 pc=0x4d8816
bytes.(*Buffer).ReadFrom(0xc000240300, 0x740d60, 0xc000282148, 0xb91098, 0xc000240300, 0xc000157f01)
        /usr/local/Cellar/go/1.12.5/libexec/src/bytes/buffer.go:205 +0x52 fp=0xc000157eb0 sp=0xc000157e40 pc=0x4d8c62
io.copyBuffer(0x740880, 0xc000240300, 0x740d60, 0xc000282148, 0x0, 0x0, 0x0, 0x404ce5, 0xc0000387e0, 0xc000157fb0)
        /usr/local/Cellar/go/1.12.5/libexec/src/io/io.go:388 +0x303 fp=0xc000157f28 sp=0xc000157eb0 pc=0x46dc73
io.Copy(...)
        /usr/local/Cellar/go/1.12.5/libexec/src/io/io.go:364
os/exec.(*Cmd).writerDescriptor.func1(0xc0000387e0, 0xc000157fb0)
        /usr/local/Cellar/go/1.12.5/libexec/src/os/exec/exec.go:288 +0x6a fp=0xc000157fa0 sp=0xc000157f28 pc=0x65166a
os/exec.(*Cmd).Start.func1(0xc00025fa20, 0xc000110ae0)
        /usr/local/Cellar/go/1.12.5/libexec/src/os/exec/exec.go:409 +0x2e fp=0xc000157fd0 sp=0xc000157fa0 pc=0x6516fe
runtime.goexit()
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000157fd8 sp=0xc000157fd0 pc=0x457b81
created by os/exec.(*Cmd).Start
        /usr/local/Cellar/go/1.12.5/libexec/src/os/exec/exec.go:408 +0x5ed

goroutine 1 [syscall, 256 minutes, locked to thread]:
syscall.Syscall(0x7fff462a2270, 0x2, 0x138, 0xffffffff, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.5/libexec/src/runtime/syscall_windows.go:184 +0xea
syscall.WaitForSingleObject(0x138, 0xffffffff, 0x5, 0x20, 0x7384ca)
        /usr/local/Cellar/go/1.12.5/libexec/src/syscall/zsyscall_windows.go:738 +0x6b
os.(*Process).wait(0xc00028c5a0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.5/libexec/src/os/exec_windows.go:18 +0x6f
os.(*Process).Wait(...)
        /usr/local/Cellar/go/1.12.5/libexec/src/os/exec.go:125
os/exec.(*Cmd).Wait(0xc00025fa20, 0x0, 0x0)
        /usr/local/Cellar/go/1.12.5/libexec/src/os/exec/exec.go:474 +0x68
os/exec.(*Cmd).Run(0xc00025fa20, 0xc000240300, 0xc00025fa20)
        /usr/local/Cellar/go/1.12.5/libexec/src/os/exec/exec.go:318 +0x63
os/exec.(*Cmd).CombinedOutput(0xc00025fa20, 0xe, 0xc000109ca0, 0x4, 0x4, 0xc00025fa20)
        /usr/local/Cellar/go/1.12.5/libexec/src/os/exec/exec.go:534 +0xff
_/Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/execute.Execute(0xc0002137c0, 0x4a, 0x4a, 0x4b, 0xc0002137c0, 0x4a, 0x0)
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/execute/execute.go:11 +0xb5
_/Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/api.Results(0xc000054160, 0x19, 0xc000054460, 0x1f, 0xc00006f890)
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/api/api.go:51 +0xe9
main.runBeaconIteration(0xc000054160, 0x19, 0xc000054460, 0x1f, 0xc0000560c0, 0xc, 0xc000080180, 0x21)
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/sandcat.go:30 +0x3fa
main.main()
        /Users/davidhunt/Desktop/toolbox/caldera/plugins/sandcat/gocat/sandcat.go:57 +0x318

**Comment by privateducky** [comment]
I haven't heard of an OOM error for the agent yet - but there are probably a number of ways to create one, based on what tests/commands you throw to it or if too many commands are run in a short time period. for instance, if the command was an endless loop, it would error out pretty quickly.

I'd be open to adjusting how we execute commands (execute.go) in the agent to be more resilient regardless of the command thrown to it-- but in "normal" operations we haven't experienced this need yet. we'll keep this on the back-burner for now, but if you want to take a swing at this, I'm happy o review.

**Comment by khyberspache** [comment]
Do you know what specific command caused the agent to try to allocate 17Gb of memory? Right now we are collecting the combined stdout/stderr and sending it back to the server. Either there is a memory leak in our agent's command execution implementation, or the command you ran generated an excessive amount of data to stdout/stderr.  

Can you try to recreate this error?

**Comment by scottma** [comment]
What I did was to convert all the redcanary tests to caldera format and run them by tactics under one adversary. This issue happened when running Windows related tests. There were a total of~240 tests. It was being run by tactics in sequential order. I tried different combinations, I finally got it working by divided it into seperate adversaries, max 50 attacks & max 5 tactics per adversary. The same tests run just fine. I notice, if I schedule all 4-5 advarsaries at the same time, 2 of them run somewhat concurrently. 

I suspect it has to do with the ordering of the original tests. I can see if I can reproduce it and nail it down to the tests that it was running when it encountered the out of memory scenarios.

**Comment by khyberspache** [comment]
Based upon what you're describing, it might be an issue with how an agent collects and stores all of the schedule operations. The server will send all of the scheduled tasks for a phase to an agent to execute.  If you were to schedule 4-5 adversaries concurrently on the same agent with, say, 100 tests in a single phase, that would be 400-500 tests in memory at a time per phase.  I still don't think that is the issue though... Seems like there might be a memory leak somewhere and seeing as we are using GOLang agents, it might be an implementation issue on our end.

**Comment by privateducky** [comment]
closing due to inactivity. this issue is not on our radar to fix, as we haven't experienced it inside an operation (yet).
