### ISSUE TITLE
Enumerate domain computers Fails - Request Entity Too Large

### ISSUE THREAD

**Issue by adamsh25** [mitre/caldera#39]
Exception on computer enumeration

Traceback (most recent call last):
  File "/home/javelin/Downloads/caldera-master/caldera/app/api.py", line 122, in entrypoint
    resp = await decorated(req, token, req.match_info)
  File "/home/javelin/Downloads/caldera-master/caldera/app/api.py", line 84, in decorated
    results = await f(req, **kwargs)
  File "/home/javelin/Downloads/caldera-master/caldera/app/api.py", line 223, in query_job
    json = await request.json()
  File "/var/attack/lib/python3.6/site-packages/aiohttp/web_request.py", line 512, in json
    body = yield from self.text()
  File "/var/attack/lib/python3.6/site-packages/aiohttp/web_request.py", line 505, in text
    bytes_body = yield from self.read()
  File "/var/attack/lib/python3.6/site-packages/aiohttp/web_request.py", line 496, in read
    raise HTTPRequestEntityTooLarge
aiohttp.web_exceptions.HTTPRequestEntityTooLarge: Request Entity Too Large

- runs on venv 
- pip 10.0.1

whenever my agents are trying to enumerate domain computers, I receive this message.
Seems like you need to raise the max size of HTTP req threshold.

**Comment by dm-mitre** [comment]
Thanks for reporting this. We will have to increase the request size.
