### ISSUE TITLE
TimestampModified error when running timestomp

### ISSUE THREAD

**Issue by chrisnewmanuk** [mitre/caldera#5]
As below:

INFO:app.operation.operation:Running step timestomp
INFO:app.server:Planner closed
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/caldera/caldera/app/server.py", line 165, in sigint_handler
    target()
  File "/home/user/caldera/caldera/app/server.py", line 306, in planner_process
    loop.run_until_complete(start_operations(rebuild_mappings))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/user/caldera/caldera/app/updates.py", line 127, in start_operations
    await s.loop()
  File "/home/user/caldera/caldera/app/operation/operation.py", line 299, in loop
    await self._perform_next_step()
  File "/home/user/caldera/caldera/app/operation/operation.py", line 612, in _perform_next_step
    success = await next_step.action(*args)
  File "/home/user/caldera/caldera/app/operation/operation_steps.py", line 453, in action
    if results["TimestampModified"] == "True":
KeyError: 'TimestampModified'

JSON for the job:
  {
    "_id": "5a2a786d1d41c807b5a8c248",
    "agent": "5a250ff31d41c80a1fa300b8",
    "action": {
      "rats": {
        "hostname": "win8calderavictim",
        "name": 3708,
        "function": "execute",
        "parameters": {
          "command_line": "powershell -command -",
          "stdin": "[[timestomper]] Perform-Timestomp -FileLocation \"C:\\Users\\All Users\\Microsoft\\User Account Pictures\\Administrator.dat\" -Verbose None"
        }
      },
      "result": {
        "pid": "2104",
        "stdout": "Perform-Timestomp : A positional parameter cannot be found that accepts \r\nargument 'None'.\r\nAt line:1 char:2\r\n+  Perform-Timestomp -FileLocation \"C:\\Users\\All Users\\Microsoft\\User Account \r\nPict ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n~~~\r\n    + CategoryInfo          : InvalidArgument: (:) [Perform-Timestomp], Parame \r\n   terBindingException\r\n    + FullyQualifiedErrorId : PositionalParameterNotFound,Perform-Timestomp\r\n \r\n"
      }
    },
    "create_time": "2017-12-08T11:33:01.718Z",
    "status": "success"
  }
]

**Comment by cl-mitre** [comment]
Thanks for reporting this. We've identified the cause, and are working on a patch for both the root and the crash.

**Comment by dm-mitre** [comment]
@chrisnewmanuk I believe we fixed this in 4c09533533d05799728e758ac063bde0a1b7c0a6
sorry this took us so long to post
