### ISSUE TITLE
all operation does not Start 

### ISSUE THREAD

**Issue by Iwatch31** [mitre/caldera#566]
Hey, 

I'm using the lastest  version of caldera (master branch) with plugins : 
stockpile, sandcat, gui, chain, caltack, evals

when I start my operation this one causes this error : 
```

ERROR:aiohttp.server:Error handling request
caldera_1  | Traceback (most recent call last):
caldera_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 390, in start
caldera_1  |     resp = await self._request_handler(request)
caldera_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 366, in _handle
caldera_1  |     resp = await handler(request)
caldera_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 106, in impl
caldera_1  |     return await handler(request)
caldera_1  |   File "/usr/local/lib/python3.7/site-packages/aiohttp_session/__init__.py", line 152, in factory
caldera_1  |     response = await handler(request)
caldera_1  |   File "/usr/src/app/plugins/chain/app/chain_api.py", line 38, in rest_api
caldera_1  |     base = await self.rest_core(request)
caldera_1  |   File "/usr/src/app/plugins/chain/app/chain_api.py", line 66, in rest_core
caldera_1  |     output = await options[request.method][index](data)
caldera_1  |   File "/usr/src/app/plugins/chain/app/chain_api.py", line 53, in <lambda>
caldera_1  |     core_operation=lambda d: self.data_svc.create_operation(**d),
caldera_1  | TypeError: create_operation() got an unexpected keyword argument 'stealth'
```

**Comment by privateducky** [comment]
it looks like your plugins are not aligned with the core code. this is a common problem if you are running against the master (bleeding-edge) code base.

the easiest way to solve this is to re-clone the project.

alternatively, you can clone a specific release version (see the README).

**Comment by Iwatch31** [comment]
solve
