### ISSUE TITLE
terminal plugins doesn't start

### ISSUE THREAD

**Issue by Iwatch31** [mitre/caldera#567]
hey, 

When i try to activate terminal plugins at start of the server this error appear :

```
caldera_1  | DEBUG:root:Loading plugin: stockpile
caldera_1  | DEBUG:root:Loading plugin: sandcat
caldera_1  | DEBUG:root:Loading plugin: gui
caldera_1  | DEBUG:root:Loading plugin: chain
caldera_1  | DEBUG:root:Loading plugin: terminal
caldera_1  | Traceback (most recent call last):
caldera_1  |   File "server.py", line 96, in <module>
caldera_1  |     plugin_modules = build_plugins(cfg['plugins'])
caldera_1  |   File "server.py", line 43, in build_plugins
caldera_1  |     modules.append(import_module('plugins.%s.hook' % plug))
caldera_1  |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
caldera_1  |     return _bootstrap._gcd_import(name[level:], package, level)
caldera_1  |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
caldera_1  |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
caldera_1  |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
caldera_1  |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
caldera_1  |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
caldera_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
caldera_1  |   File "/usr/src/app/plugins/terminal/hook.py", line 5, in <module>
caldera_1  |     from pyfiglet import Figlet
caldera_1  | ModuleNotFoundError: No module named 'pyfiglet'
```
thanks for your response

**Comment by privateducky** [comment]
Install the requirements.txt for any loaded plugin
