### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by omergunal** [mitre/caldera#57]
system: ubuntu 14.04
```
gunal@ubuntu:~/caldera$ sudo docker-compose up
Building server
Step 1/10 : FROM python:3.6
3.6: Pulling from library/python
55cbf04beb70: Already exists
1607093a898c: Download complete
 10.74MB/10.74MBwnload complete
d4eee24d4dac: Downloading [==========>                                        ]  10.14MB/50.06MBiting
b023afffd10b: Waiting
4d4eb448d315: Waiting
c4eb58602129: Waiting
598629fb90fc: Waiting
Traceback (most recent call last):
  File "bin/docker-compose", line 6, in <module>
  File "compose/cli/main.py", line 71, in main
  File "compose/cli/main.py", line 124, in perform_command
  File "compose/cli/main.py", line 959, in up
  File "compose/project.py", line 452, in up
  File "compose/service.py", line 324, in ensure_image_exists
  File "compose/service.py", line 972, in build
  File "compose/progress_stream.py", line 18, in stream_output
  File "compose/utils.py", line 61, in split_buffer
  File "compose/utils.py", line 37, in stream_as_text
  File "site-packages/docker/api/client.py", line 304, in _stream_helper
  File "site-packages/urllib3/response.py", line 401, in read
  File "contextlib.py", line 35, in __exit__
  File "site-packages/urllib3/response.py", line 320, in _error_catcher
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Failed to execute script docker-compose
```

**Comment by hf-mitre** [comment]
This looks like something interrupted Docker's connection to Docker hub when it was pulling in images.  
Try it again? 

This looks like a networking issue to me, but if it recurs on a regular basis you might try upgrading/downgrading the versions of docker and docker compose, or checking out the issue tracker at docker-compose https://github.com/docker/compose/issues .  

Also, Ubuntu 14.04's hits end of life next year and might be using an older version of Docker.  If you installed Docker.io using `apt` you might consider installing a newer docker version with the steps here https://docs.docker.com/install/linux/docker-ce/ubuntu/
