### ISSUE TITLE
ERROR - install from source code

### ISSUE THREAD

**Issue by omergunal** [mitre/caldera#64]
I wrote this command before run caldera.py
System: ubuntu 16.04
```
echo "replSet = caldera" >> /etc/mongodb.conf
```

```
python3.5 caldera.py 
INFO:app.engine.database:Performing first time replication set initialization on MongoDB
Traceback (most recent call last):
  File "/root/caldera/caldera/app/engine/database.py", line 51, in initialize
    a = next(oplog.find().sort('$natural', pymongo.DESCENDING).limit(-1))['ts']
  File "/usr/local/lib/python3.5/dist-packages/pymongo/cursor.py", line 1197, in next
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "caldera.py", line 24, in <module>
    server.run(debug=debug)
  File "/root/caldera/caldera/app/server.py", line 111, in run
    database.initialize(settings['database']['key'], settings['database']['host'], settings['database']['port'])
  File "/root/caldera/caldera/app/engine/database.py", line 54, in initialize
    _setup_replica_set(host, port)
  File "/root/caldera/caldera/app/engine/database.py", line 33, in _setup_replica_set
    c.admin.command("replSetInitiate", config)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/database.py", line 614, in command
    codec_options, session=session, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/database.py", line 514, in _command
    client=self.__client)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/pool.py", line 579, in command
    unacknowledged=unacknowledged)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/network.py", line 150, in command
    parse_write_concern_error=parse_write_concern_error)
  File "/usr/local/lib/python3.5/dist-packages/pymongo/helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: server is not running with --replSet
```

**Comment by wietze** [comment]
Are you sure you have used the correct syntax? The [MongoDB manual](https://docs.mongodb.com/manual/administration/configuration/#replication-configuration) suggests you're using the old syntax rather than the new YAML syntax.

**Comment by omergunal** [comment]
@wietze  this is my /etc/mongodb.conf file:
```
# mongodb.conf

# Where to store the data.
dbpath=/var/lib/mongodb

#where to log
logpath=/var/log/mongodb/mongodb.log

logappend=true

bind_ip = 127.0.0.1
#port = 27017

# Enable journaling, http://www.mongodb.org/display/DOCS/Journaling
journal=true

# Enables periodic logging of CPU utilization and I/O wait
#cpu = true

# Turn on/off security.  Off is currently the default
#noauth = true
#auth = true

# Verbose logging output.
#verbose = true

# Inspect all client data for validity on receipt (useful for
# developing drivers)
#objcheck = true

# Enable db quota management
#quota = true

# Set oplogging level where n is
#   0=off (default)
#   1=W
#   2=R
#   3=both
#   7=W+some reads
#oplog = 0

# Diagnostic/debugging option
#nocursors = true

# Ignore query hints
#nohints = true

# Disable the HTTP interface (Defaults to localhost:27018).
#nohttpinterface = true

# Turns off server-side scripting.  This will result in greatly limited
# functionality
#noscripting = true

# Turns off table scans.  Any query that would do a table scan fails.
#notablescan = true

# Disable data file preallocation.
#noprealloc = true

# Specify .ns file size for new databases.
# nssize = <size>

# Accout token for Mongo monitoring server.
#mms-token = <token>

# Server name for Mongo monitoring server.
#mms-name = <server-name>

# Ping interval for Mongo monitoring server.
#mms-interval = <seconds>

# Replication Options

# in replicated mongo databases, specify here whether this is a slave or master
#slave = true
#source = master.example.com
# Slave only: specify a single database to replicate
#only = master.example.com
# or
#master = true
#source = slave.example.com

# Address of a server to pair with.
#pairwith = <server:port>
# Address of arbiter server.
#arbiter = <server:port>
# Automatically resync if slave data is stale
#autoresync
# Custom size for replication operation log.
#oplogSize = <MB>
# Size limit for in-memory storage of op ids.
#opIdMem = <bytes>

# SSL options
# Enable SSL on normal ports
#sslOnNormalPorts = true
# SSL Key file and password
#sslPEMKeyFile = /etc/ssl/mongodb.pem
#sslPEMKeyPassword = pass
replSet = caldera
```

**Comment by lisicn** [comment]
@omergunal 
I did encounter this problem, but I am not sure whether it is related to the configuration file. I chose the third installation method. The environment is windows7. You can try this when starting the database.
`mongod.exe --dbpath=e:\ssd_app\mongodb\data\db  --replSet caldera`
 If you have problems, I guess it should be Configuration file has a relationship

**Comment by omergunal** [comment]
Thanks @qq854051086 .but i am using ubuntu 16.04 . Can you write command for ubuntu?
