### ISSUE TITLE
Trouble building Caldera using build.py

### ISSUE THREAD

**Issue by SpaceAether** [mitre/caldera#68]
Hello, I am having some trouble building an executable using build.py script.

First, when I launch the script I get the following error :
```
Traceback (most recent call last):
  File ".\build.py", line 15, in <module>
    subprocess.run(cmd)
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\username\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Pyinstaller is not installed on the system, it might be nice to add a requirements file for the build script with the required packages.

After installing it, I relaunched it and got another error : 
```
385 INFO: PyInstaller: 3.4
388 INFO: Python: 3.6.5
389 INFO: Platform: Windows-10-10.0.14393-SP0
400 INFO: wrote C:\Users\username\Documents\caldera-master\caldera-master\caldera\caldera.spec
404 INFO: UPX is not available.
415 INFO: Extending PYTHONPATH with paths
['C:\\Users\\username\\Documents\\caldera-master\\caldera-master',
 'C:\\Users\\username\\Documents\\caldera-master\\caldera-master\\caldera']
418 INFO: checking Analysis
419 INFO: Building Analysis because Analysis-00.toc is non existent
419 INFO: Initializing module dependency graph...
429 INFO: Initializing module graph hooks...
445 INFO: Analyzing base_library.zip ...
11867 INFO: Analyzing hidden import '_cffi_backend'
11870 INFO: running Analysis Analysis-00.toc
11926 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\username\appdata\local\programs\python\python36\python.exe
11987 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python.exe
12031 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python.exe
12075 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python.exe
12125 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python.exe
12260 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python.exe
12355 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\VCRUNTIME140.dll
12405 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\VCRUNTIME140.dll
12478 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\VCRUNTIME140.dll
12552 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\VCRUNTIME140.dll
12647 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\VCRUNTIME140.dll
13028 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python36.dll
13106 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python36.dll
13192 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python36.dll
13279 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python36.dll
13357 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python36.dll
13444 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python36.dll
13566 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python36.dll
13643 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python36.dll
13729 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python36.dll
13827 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python36.dll
13914 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python36.dll
13995 WARNING: lib not found: api-ms-win-crt-process-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\python36.dll
14004 INFO: Caching module hooks...
14015 INFO: Analyzing C:\Users\username\Documents\caldera-master\caldera-master\caldera\caldera.py
21696 INFO: Processing pre-find module path hook   distutils
23804 INFO: Processing pre-safe import module hook   six.moves
27082 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
31679 INFO: Loading module hooks...
31682 INFO: Loading module hook "hook-certifi.py"...
31688 INFO: Loading module hook "hook-cryptography.py"...
32577 INFO: Loading module hook "hook-distutils.py"...
32581 INFO: Loading module hook "hook-encodings.py"...
32787 INFO: Loading module hook "hook-jinja2.py"...
32842 INFO: Loading module hook "hook-lib2to3.py"...
32895 INFO: Loading module hook "hook-pkg_resources.py"...
33867 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
33963 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
34094 INFO: Loading module hook "hook-pydoc.py"...
34096 INFO: Loading module hook "hook-sysconfig.py"...
34101 INFO: Loading module hook "hook-xml.py"...
34371 INFO: Looking for ctypes DLLs
34410 INFO: Analyzing run-time hooks ...
34423 INFO: Including run-time hook 'pyi_rth_pkgres.py'
34429 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
34466 INFO: Looking for dynamic libraries
34514 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_decimal.pyd
34552 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_decimal.pyd
34593 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_decimal.pyd
34631 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_decimal.pyd
34668 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_decimal.pyd
34704 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_decimal.pyd
34750 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_decimal.pyd
34796 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_ctypes.pyd
34842 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_ctypes.pyd
34887 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_ctypes.pyd
34934 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_multiprocessing.pyd
35015 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_ssl.pyd
35053 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_ssl.pyd
35102 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_ssl.pyd
35142 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_ssl.pyd
35211 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_ssl.pyd
35334 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_ssl.pyd
35386 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_ssl.pyd
35430 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_ssl.pyd
35473 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_ssl.pyd
35539 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_ssl.pyd
35605 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\unicodedata.pyd
35639 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\unicodedata.pyd
35684 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\unicodedata.pyd
35725 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\pyexpat.pyd
35760 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\pyexpat.pyd
35795 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\pyexpat.pyd
35830 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\pyexpat.pyd
35870 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\pyexpat.pyd
35932 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_hashlib.pyd
35967 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_hashlib.pyd
36003 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_hashlib.pyd
36039 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_hashlib.pyd
36080 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_hashlib.pyd
36114 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_hashlib.pyd
36157 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_hashlib.pyd
36197 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_hashlib.pyd
36239 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_hashlib.pyd
36282 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_bz2.pyd
36319 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_bz2.pyd
36354 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_bz2.pyd
36389 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_bz2.pyd
36434 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_bz2.pyd
36478 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_lzma.pyd
36513 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_lzma.pyd
36560 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_socket.pyd
36601 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_socket.pyd
36653 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\select.pyd
36708 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\_cffi_backend.cp36-win_amd64.pyd
36751 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\_cffi_backend.cp36-win_amd64.pyd
36798 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\_cffi_backend.cp36-win_amd64.pyd
36840 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\_cffi_backend.cp36-win_amd64.pyd
36878 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\_cffi_backend.cp36-win_amd64.pyd
36929 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\_cffi_backend.cp36-win_amd64.pyd
36987 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\cryptography\hazmat\bindings\_constant_time.pyd
37059 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\cryptography\hazmat\bindings\_padding.pyd
37149 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\cryptography\hazmat\bindings\_openssl.pyd
37187 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\cryptography\hazmat\bindings\_openssl.pyd
37228 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\cryptography\hazmat\bindings\_openssl.pyd
37266 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\cryptography\hazmat\bindings\_openssl.pyd
37311 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\cryptography\hazmat\bindings\_openssl.pyd
37348 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\cryptography\hazmat\bindings\_openssl.pyd
37401 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\cryptography\hazmat\bindings\_openssl.pyd
37441 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\cryptography\hazmat\bindings\_openssl.pyd
37477 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\cryptography\hazmat\bindings\_openssl.pyd
37538 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\pymongo\_cmessage.cp36-win_amd64.pyd
37575 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\pymongo\_cmessage.cp36-win_amd64.pyd
37624 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\pymongo\_cmessage.cp36-win_amd64.pyd
37667 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\pymongo\_cmessage.cp36-win_amd64.pyd
37728 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\bson\_cbson.cp36-win_amd64.pyd
37767 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\bson\_cbson.cp36-win_amd64.pyd
37809 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\bson\_cbson.cp36-win_amd64.pyd
37852 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\bson\_cbson.cp36-win_amd64.pyd
37909 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\ujson.cp36-win_amd64.pyd
37951 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\ujson.cp36-win_amd64.pyd
37989 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\ujson.cp36-win_amd64.pyd
38028 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\ujson.cp36-win_amd64.pyd
38077 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\ujson.cp36-win_amd64.pyd
38133 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\pyDatalog\pyEngine.cp36-win_amd64.pyd
38196 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\markupsafe\_speedups.cp36-win_amd64.pyd
38256 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\aiohttp\_websocket.cp36-win_amd64.pyd
38319 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\aiohttp\_http_parser.cp36-win_amd64.pyd
38366 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\aiohttp\_http_parser.cp36-win_amd64.pyd
38425 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\multidict\_multidict.cp36-win_amd64.pyd
38507 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\aiohttp\_frozenlist.cp36-win_amd64.pyd
38593 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\lib\site-packages\yarl\_quoting.cp36-win_amd64.pyd
38665 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_asyncio.pyd
38730 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_overlapped.pyd
38769 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\username\appdata\local\programs\python\python36\DLLs\_overlapped.pyd
38774 INFO: Looking for eggs
38777 INFO: Using Python library c:\users\username\appdata\local\programs\python\python36\python36.dll
38778 INFO: Found binding redirects:
[]
38800 INFO: Warnings written to ..\build\caldera\warn-caldera.txt
39124 INFO: Graph cross-reference written to ..\build\caldera\xref-caldera.html
39184 INFO: Appending 'datas' from .spec
39219 INFO: checking PYZ
39219 INFO: Building PYZ because PYZ-00.toc is non existent
39223 INFO: Building PYZ (ZlibArchive) ..\build\caldera\PYZ-00.pyz
41593 INFO: Building PYZ (ZlibArchive) ..\build\caldera\PYZ-00.pyz completed successfully.
41653 INFO: checking PKG
41654 INFO: Building PKG because PKG-00.toc is non existent
41657 INFO: Building PKG (CArchive) PKG-00.pkg
41730 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
41734 INFO: Bootloader c:\users\username\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
41735 INFO: checking EXE
41736 INFO: Building EXE because EXE-00.toc is non existent
41736 INFO: Building EXE from EXE-00.toc
41738 INFO: Appending archive to EXE ..\build\caldera\caldera.exe
41750 INFO: Building EXE from EXE-00.toc completed successfully.
41757 INFO: checking COLLECT
41758 INFO: Building COLLECT because COLLECT-00.toc is non existent
41760 INFO: Building COLLECT COLLECT-00.toc
43390 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```

The module win32com is missing so I installed pypiwin32 package but concerning the lib not found api-ms-win-* I didn't found how to solve the warning.

I relaunched the build and obtained almost the same (minus the one concerning the win32com module)

I then tried to launch the created executable and got the following error : 
```
Error loading Python DLL 'C:\Users\username\Documents\caldera-master\caldera-master\build\caldera\python36.dll'.
LoadLibrary: The specified module could not be found.
```

It seems that the python36.dll library is missing while in reality it is in the dist folder instead of the build folder. 
Is it normal that it is not looking in the right directory or are the files placed in the wrong directory ?

To prevent this problem I copied the content of the dist folder inside the build folder.

But there still is a problem when launching caldera.exe : 
```
Traceback (most recent call last):
  File "caldera\caldera.py", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\username\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "caldera\app\server.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\username\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "caldera\app\views.py", line 33, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\username\\Documents\\caldera-master\\caldera-master\\build\\caldera\\app\\../VERSION'
[10600] Failed to execute script caldera
```

There is no VERSION file in the folder. I made a copy of the one in the repository and put it in.

I then created the folder with CraterMain.exe in the right place to be detected by the executable.

And again, another error at launch : 
```
ERROR:app.server:No directory exists at 'C:\Users\username\Documents\caldera-master\caldera-master\build\caldera\www\static\css'
Traceback (most recent call last):
  File "site-packages\aiohttp\web_urldispatcher.py", line 481, in __init__
ValueError: Not a directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "caldera\app\server.py", line 124, in run
  File "caldera\app\server.py", line 183, in web_process
  File "caldera\app\views.py", line 366, in init
  File "caldera\app\views.py", line 364, in add_rsrc
  File "site-packages\aiohttp\web_urldispatcher.py", line 926, in add_static
  File "site-packages\aiohttp\web_urldispatcher.py", line 484, in __init__
ValueError: No directory exists at 'C:\Users\username\Documents\caldera-master\caldera-master\build\caldera\www\static\css'
```

The www folder is not in the folder, I made a copy in the required directory

And finally, I was able to launch the server and got it working but with still a problem.
```
DEBUG:asyncio:Using selector: SelectSelector
INFO:app.server:Serving on 0.0.0.0:8888
DEBUG:asyncio:Using selector: SelectSelector
ERROR:app.server:[Errno 10048] error while attempting to bind on address ('0.0.0.0', 8888): only one usage of each socket address (protocol/network address/port) is normally permitted
Traceback (most recent call last):
  File "asyncio\base_events.py", line 1045, in create_server
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "caldera\app\server.py", line 124, in run
  File "caldera\app\server.py", line 263, in web_process
  File "asyncio\base_events.py", line 468, in run_until_complete
  File "asyncio\base_events.py", line 1049, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('0.0.0.0', 8888): only one usage of each socket address (protocol/network address/port) is normally permitted

DEBUG:asyncio:Using selector: SelectSelector
ERROR:app.server:[Errno 10048] error while attempting to bind on address ('0.0.0.0', 8888): only one usage of each socket address (protocol/network address/port) is normally permitted
Traceback (most recent call last):
  File "asyncio\base_events.py", line 1045, in create_server
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "caldera\app\server.py", line 124, in run
  File "caldera\app\server.py", line 263, in web_process
  File "asyncio\base_events.py", line 468, in run_until_complete
  File "asyncio\base_events.py", line 1049, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('0.0.0.0', 8888): only one usage of each socket address (protocol/network address/port) is normally permitted
```

As you can see the server has been launched and is working, but it keep trying to launch new instance of it again and again but it can't because the port is already in use by the first instance of the server.

My questions are : 
* Do you think I made the correct operations to make it work ?
* Could you please detail how you are building the application to get it working correctly ?
* Do you have any idea how I can prevent the application from trying to launch multiple servers instance and only keep one ?

Thanks in advance

**Comment by cl-mitre** [comment]
Before I start trying to help you debug this, I need to point out that Caldera does not officially support the process of making an executable for the server via pyinstaller, rather it expects the server to be run as a script using python (hence the lack of a requirement for pyinstaller). As such, the team lacks a defined process for building an executable version of the server. That being noted, the build.py file you found is the result of an attempt the team made at the aforementioned process that was abandoned nearly a year ago, and will likely be removed in the next release. 

Now, the first thing I can suggest is looking into getting a copy of the Microsoft Visual C++ 2015 redistributable, as that is what contains the api's that are throwing the error during the build process. As for moving things around for the build process, although I can't seem to replicate the circumstances locally at the moment, your actions make sense in the context you've presented them.

**Comment by privateducky** [comment]
Closing due to inactivity.
