### ISSUE TITLE
Bug about operations‘ tab?

### ISSUE THREAD

**Issue by J4son** [mitre/caldera#7]
I created new operation, but I don't want to use it any more. I clicked delete in view operations tab, but nothing happend. I don't know how delete it, who can help me ?　Error like blow.
  File "C:\Users\lpc\Desktop\caldera\caldera\app\engine\objects.py", line 153,
n wait_till_completed
    await waiter_task
  File "C:\Users\lpc\AppData\Local\Programs\Python\Python35\lib\asyncio\future
py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\lpc\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.
", line 310, in _wakeup
    future.result()
  File "C:\Users\lpc\AppData\Local\Programs\Python\Python35\lib\asyncio\future
py", line 286, in result
    raise CancelledError
concurrent.futures._base.CancelledError
Traceback (most recent call last):
  File "C:\Users\lpc\Desktop\caldera\caldera\app\api.py", line 122, in entrypo
t
    resp = await decorated(req, token, req.match_info)
  File "C:\Users\lpc\Desktop\caldera\caldera\app\api.py", line 84, in decorate
    results = await f(req, **kwargs)
  File "C:\Users\lpc\Desktop\caldera\caldera\app\api.py", line 732, in generat
_dispatcher
    await job.wait_till_completed()
  File "C:\Users\lpc\Desktop\caldera\caldera\app\engine\objects.py", line 153,
n wait_till_completed
    await waiter_task
  File "C:\Users\lpc\AppData\Local\Programs\Python\Python35\lib\asyncio\future
py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "C:\Users\lpc\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.
", line 310, in _wakeup
    future.result()
  File "C:\Users\lpc\AppData\Local\Programs\Python\Python35\lib\asyncio\future
py", line 286, in result
    raise CancelledError

**Comment by dm-mitre** [comment]
If you click on the operation it should bring you into the detailed view. You will see a red button to Cancel the operation. Clicking that should cancel the operation. If the operation is in a waiting state, you may need to restart the server after performing the Cancel to get the operation to actually cancel. Once it is canceled you should be able to delete it.

**Comment by J4son** [comment]
I click cancel button, but seems that nothing happened. Another operation detail is not have cancel button, I click it before, that means I can delete? But still delete.

**Comment by J4son** [comment]
I restart my server's caldera py, info like that.
DEBUG:app.server:Planner has started
DEBUG:asyncio:Using selector: SelectSelector
DEBUG:asyncio:Using selector: SelectSelector
INFO:app.server:Serving on 0.0.0.0:8888
INFO:app.server:Planner closed
Process Process-1:

**Comment by dm-mitre** [comment]
The "Planner closed" line indicates that the planning process died. Did you press ctrl+c to kill or was there an error?

**Comment by J4son** [comment]
I don't do anthing, I start server and delete operation. Then these info show.

**Comment by dm-mitre** [comment]
I think the crash from your other issue is impacting this. To recover from this state the process is 
1. Open the detailed view of the operation
2. If it is stuck in "bootstrapping" mode, press cancel
3. Restart the server (python) process
4. On restart the operation state should change to "complete"
5. It can now be deleted.
