### ISSUE TITLE
Adding Scripts Not Showing Up?

### ISSUE THREAD

**Issue by ms08067** [mitre/caldera#73]
Running Caldera Server on Ubuntu 16. Downloaded an external powershell script and attempted to encode using encode.py. Seems to execute just fine. I move it to the folder that contains the scripts however it does not show up in the script editor. It does not appear that it 'knows' about the 'imported' or 'added' script.

**Comment by cl-mitre** [comment]
It seems to be working on my end. Can you verify the following for me:

1) You placed the new script in the \caldera\caldera\files\ directory
2) You refreshed the Caldera app (either open a new tab or hit F5)

If the problem persists, let me know and I'll see if I can troubleshoot further.

**Comment by ms08067** [comment]
[https://imgur.com/a/A4WjmbN](url)

1st Step: grab a raw powershell script from github.
2nd Step: Copy and Pasted into nano inveigh.ps1, saved file
3rd Step: Used encoder.py from caldera with -i and -o options
4th Step: mv inveigh.ps1 into the files folder

I have tried refreshing, and restarting caldera as well. The script editor just wont show up with the new powershell script. I was just testing to see if I could add other scripts, It doesn't have to be the inveigh ps1 script, I am willing to try anything.

**Comment by ms08067** [comment]
I also just followed documentation on adding a step. I cannot get the step to show up when creating an adversary. I am using docker-compose up to spin up, i also have cleared browser cache. It doesn't seem like any changes I make take. Any thoughts ?

**Comment by unkempthenry** [comment]
Hi @ms08067, 

Did you rebuild the docker image and redeploy the container after you made the changes?
```
docker-compose build 
docker-compose up 
```

BTW, your name made me laugh.  Thanks!

**Comment by ms08067** [comment]
It builds just fine but following the documentation on adding a step, I did it verbatim..

server_1  |   File "/opt/caldera/caldera/app/operation/operation_steps.py", line 1779, in PEMCollection
server_1  |     format(host.hostname)
server_1  | NameError: name 'host' is not defined 

BTW, thanks for the comment ;) Only us nerds know whats up.

**Comment by unkempthenry** [comment]
Can you post the pre and postconditions for the step you're adding as well as the line that declares the action method?

The `host` variable isn't declared in the step but it is being used.  You want to make sure that all the parameters/variables being passed to `action` on your step match the preconditions and postconditions.  This allows CALDERA to pass the right knowledge object to your step. 

If your step is meant to execute locally (or collect data locally) you may also want to just try using `rat.host.hostname` instead of `host.hostname`.

**Comment by ms08067** [comment]
Let me go back to the original issue before I run off on this other trail. So I was able to get the script to show up under the editor however now its telling me this:

Warning: This filetype is not currently supported by the editor 

Its a ps1 file, and encoded using the encoder.py script. Any thoughts ?

Specifically, the source of the script is here:

[https://raw.githubusercontent.com/Kevin-Robertson/Inveigh/master/Inveigh.ps1](url)

**Comment by cl-mitre** [comment]
Yes, it's because of the extension (the built-in files are extensionless). If the filename is _x.ps1_, CALDERA will throw that error because it's looking for files that have filenames with **x-ps1**, not _x.ps1_. It's just a simplistic mechanism to keep the editor from manipulating/displaying filetypes that aren't expected (.exe, .dll, etc.). 

For clarity, the target flow is such:
1) python encode.py -i _file.ps1_ -o **file-ps1**
2) copy **file-ps1** to \files
3) view/edit in the caldera web app

Hopefully the name change should fix the problem.

**Comment by tdrlocal** [comment]
> Yes, it's because of the extension (the built-in files are extensionless). If the filename is _x.ps1_, CALDERA will throw that error because it's looking for files that have filenames with **x-ps1**, not _x.ps1_. It's just a simplistic mechanism to keep the editor from manipulating/displaying filetypes that aren't expected (.exe, .dll, etc.).
> 
> For clarity, the target flow is such:
> 
> 1. python encode.py -i _file.ps1_ -o **file-ps1**
> 2. copy **file-ps1** to \files
> 3. view/edit in the caldera web app
> 
> Hopefully the name change should fix the problem.

Hi, 

I tried with the command above and it throws error:
$python encode.py -i Invoke-Cats.ps1 -o Invoke-Cats-ps1
Traceback (most recent call last):
  File "encode.py", line 50, in <module>
    outf = sys.stdout.buffer
AttributeError: 'file' object has no attribute 'buffer'

When issued with python3, it does not complain. I've copied to the caldera/caldera/files dir and able to view in the web app. But I'm getting garbage output, i.e not really readable powershell script.
