### ISSUE TITLE
asyncio issue in server.py? - AttributeError: module 'asyncio' has no attribute 'create_task'

### ISSUE THREAD

**Issue by juju4** [mitre/caldera#752]
I have an ansible role to deploy caldera and it fails on HEAD since about 10 days

last successful: https://travis-ci.org/juju4/ansible-caldera/builds/604384792
example fail: https://travis-ci.org/juju4/ansible-caldera/jobs/609946907

https://travis-ci.org/juju4/ansible-caldera/jobs/609946907#L7275
```
       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]: DEBUG:data_svc:Loaded 1 sources

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]: DEBUG:data_svc:Loaded 1 planners

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]: Traceback (most recent call last):

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:   File "/var/_caldera/caldera/server.py", line 111, in <module>

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:     main(services=data_svc.get_services(), host=cfg['host'], port=cfg['port'], users=cfg['users'])

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:   File "/var/_caldera/caldera/server.py", line 82, in main

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:     loop.run_until_complete(init(host, port, services, users))

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:   File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:     return future.result()

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:   File "/var/_caldera/caldera/server.py", line 65, in init

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:     await runner.setup()

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:   File "/var/_caldera/env-caldera/lib/python3.6/site-packages/aiohttp/web_runner.py", line 232, in setup

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:     self._server = await self._make_server()

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:   File "/var/_caldera/env-caldera/lib/python3.6/site-packages/aiohttp/web_runner.py", line 331, in _make_server

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:     await self._app.startup()

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:   File "/var/_caldera/env-caldera/lib/python3.6/site-packages/aiohttp/web_app.py", line 389, in startup

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:     await self.on_startup.send(self)

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:   File "/var/_caldera/env-caldera/lib/python3.6/site-packages/aiohttp/signals.py", line 34, in send

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:     await receiver(*args, **kwargs)  # type: ignore

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:   File "/var/_caldera/caldera/server.py", line 24, in background_tasks

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]:     asyncio.create_task(application.start_sniffer_untrusted_agents())

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 caldera[11431]: AttributeError: module 'asyncio' has no attribute 'create_task'

       Nov 10 13:51:21 default-HEAD-ubuntu-1804-1573393486 systemd[1]: caldera.service: Main process exited, code=exited, status=1/FAILURE
```

this seems similar to https://github.com/mitre/caldera/pull/699/files but inside server.py, probably https://github.com/mitre/caldera/commit/c995b4e3aa207264f9dad0881f4bddab97208e80

changing asyncio to app.loop allows to start server.py
Not sure about other impacts

(Ubuntu 18.04 is python 3.6.8 and same for centos7)

Thanks

**Comment by khyberspache** [comment]
This is (most likely) a compatibility issue in your python pip libraries.  Make sure that asyncio and aiohttp is updated (pip install --upgrade asyncio).  We made the above change because `app.loop` is deprecated in the newer aiohttp.

**Comment by juju4** [comment]
Thanks @khyberspache 

I'm installing pip libraries from caldera requirements.txt to virtualenv

https://travis-ci.org/juju4/ansible-caldera/jobs/609946907#L5390
```
$ sudo -E su $USER -c "env PATH=$PATH kitchen exec ${suite}-${distribution}-${version//./} -c '/var/_caldera/env-caldera/bin/pip freeze'"
-----> Execute command on default-HEAD-ubuntu-1804.
       aiohttp==3.6.2
       aiohttp-jinja2==1.2.0
       aiohttp-security==0.4.0
       aiohttp-session==2.9.0
       async-timeout==3.0.1
       attrs==19.3.0
       cffi==1.13.2
       chardet==3.0.4
       cryptography==2.8
       idna==2.8
       idna-ssl==1.1.0
       Jinja2==2.10.3
       MarkupSafe==1.1.1
       msgpack-python==0.5.6
       multidict==4.5.2
       pkg-resources==0.0.0
       pycparser==2.19
       PyYAML==5.1.2
       six==1.13.0
       typing-extensions==3.7.4.1
       yarl==1.3.0
```

no version in https://github.com/mitre/caldera/blob/master/requirements.txt
asyncio latest is 3.4.3 from 2015 https://pypi.org/project/asyncio/#history (not included)
https://pypi.org/project/aiohttp/#history = 3.6.2 from Oct 2019 (ok)

**Comment by khyberspache** [comment]
We removed the versions from request to enable compatibility across python major versions.

We should probably do a:
```
try:
    asyncio.create_task...
except AttributeError:
    app.loop.create_task...
except Exception:
    server fail
```

I'll patch that later today

**Comment by juju4** [comment]
Thanks a lot @khyberspache !

**Comment by khyberspache** [comment]
https://github.com/mitre/caldera/pull/753

Submitted a fix PR - checkout that branch and you should be good to go

**Comment by juju4** [comment]
Confirming branch works. Thanks!
https://travis-ci.org/juju4/ansible-caldera/jobs/610623553

**Comment by khyberspache** [comment]
@juju4 fix merged
