### ISSUE TITLE
Psexec_move not working

### ISSUE THREAD

**Issue by sahiluvic** [mitre/caldera#80]
Hi. Thank you for such an amazing project. I have been trying to execute psexec_move step, but it never executes. Psexec shows as downloaded in the setting tab of caldera. The error states that ps.hex file not found. However, i can see that the file exist in the directory it is trying to access. 
![psexec](https://user-images.githubusercontent.com/32345748/47521522-43757a80-d861-11e8-9243-2236412f6b54.PNG)

The error is : 

Traceback (most recent call last):
  File "C:\Users\sahil\Downloads\caldera-master\caldera\app\operation\operation_obj.py", line 139, in drop_file
    with open(file_path_src, "rb") as file:
FileNotFoundError: [Errno 2] No such file or directory: '../dep/tools/ps.hex'

//
  File "C:\Users\sahil\Downloads\caldera-master\caldera\app\operation\operation_steps.py", line 860, in action
    await operation.drop_file(rat, ps_loc, "../dep/tools/ps.hex")
  File "C:\Users\sahil\Downloads\caldera-master\caldera\app\operation\operation_obj.py", line 146, in drop_file
    raise MissingFileError("ps.hex not found. Please download it from the settings tab.")
app.operation.operation_errors.MissingFileError: ps.hex not found. Please download it from the settings tab.

![psexec](https://user-images.githubusercontent.com/32345748/47521415-f8f3fe00-d860-11e8-9845-8d41d5de370c.PNG)

Did anyone face similar issues? Any workaround?

Thanks.

**Comment by hf-mitre** [comment]
Hi @sahiluvic , sorry you're running into trouble.  

I think this might be caused by the Step using a relative path and the environment's current directory not being what's expected (something we need to better about). 

Have you tried starting CALDERA like so? 
```
cd C:\Users\sahil\Downloads\caldera-master\caldera
python caldera.py 
```

**Comment by sahiluvic** [comment]
I always started Caldera this way. Strangely, when i started it again this morning, it worked. Thank you for your quick response :)
