### ISSUE TITLE
Issue running Caldera

### ISSUE THREAD

**Issue by dnice77** [mitre/caldera#83]
Attempting to run caldera and get the following traceback:

sudo docker run --net=host caldera --database.port 27020
INFO:app.server:Creating private key for database
INFO:app.server:Setting database host to 'localhost'
INFO:app.server:Initializing database port to '27020'
INFO:app.server:Creating private authentication key
Traceback (most recent call last):
  File "caldera.py", line 24, in <module>
    server.run(debug=debug)
  File "/opt/caldera/caldera/app/server.py", line 111, in run
    database.initialize(settings['database']['key'], settings['database']['host'], settings['database']['port'])
  File "/opt/caldera/caldera/app/engine/database.py", line 51, in initialize
    a = next(oplog.find().sort('$natural', pymongo.DESCENDING).limit(-1))['ts']
  File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1189, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1087, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1558, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1511, in __start_session
    server_session = self._get_server_session()
  File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1544, in _get_server_session
    return self._topology.get_server_session()
  File "/usr/local/lib/python3.6/site-packages/pymongo/topology.py", line 427, in get_server_session
    None)
  File "/usr/local/lib/python3.6/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27020: [Errno 111] Connection refused

**Comment by omergunal** [comment]
you can try docker-compose.
```
sudo docker-compose up
```

**Comment by dnice77** [comment]
Worked like a charm bud, thank you!
