### ISSUE TITLE
ATT&CK tactics update not working

### ISSUE THREAD

**Issue by teqagogo** [mitre/caldera#85]
Hello,

got he following error only for th attack updates:

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): attack.mitre.org
DEBUG:urllib3.connectionpool:https://attack.mitre.org:443 "GET /api.php?action=ask&format=json&query=%5B%5BCategory%3ATactic%5D%5D HTTP/1.1" 404 2176

psexec still working.

tested on parrot / kali / ubuntu lts with last github update and requirements satisfied and got the same issue on all linux.

**Comment by teqagogo** [comment]
Hi,

As advised I tried to replace attack.mitre.org by attack-old.mitre.org but it seems also broken:

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): attack-old.mitre.org
DEBUG:urllib3.connectionpool:https://attack-old.mitre.org:443 "GET /api.php?action=ask&format=json&query=%5B%5BCategory%3ATactic%5D%5D HTTP/1.1" 200 2110
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): attack-old.mitre.org
DEBUG:urllib3.connectionpool:https://attack-old.mitre.org:443 "GET /api.php?action=ask&format=json&query=%5B%5BCategory%3ATechnique%5D%5D%7C%3FHas+tactic%7C%3FHas+ID%7C%3FHas+display+name%7C%3FHas+technical+description%7C%3FHas+platform%7Climit%3D9999 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): attack-old.mitre.org
DEBUG:urllib3.connectionpool:https://attack-old.mitre.org:443 "GET /wiki/Template:Ordered_Tactics HTTP/1.1" 200 5631
Traceback (most recent call last):
  File "/tools/caldera/caldera/app/api.py", line 122, in entrypoint
    resp = await decorated(req, token, req.match_info)
  File "/tools/caldera/caldera/app/api.py", line 84, in decorated
    results = await f(req, **kwargs)
  File "/tools/caldera/caldera/app/api.py", line 630, in load_attack
    attack.refresh_attack()
  File "/tools/caldera/caldera/app/attack.py", line 46, in refresh_attack
    extract_s2 = extract_s1.group()[9:-2]
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by teqagogo** [comment]
Hi, thanks, let me update, test and i get back to you

**Comment by teqagogo** [comment]
Hi, it's now working perfectly, many thanks for your prompt support !!!
Here is the log from the run after fresh git clone:
INFO:app.server:Creating private key for database
INFO:app.server:Setting database host to 'localhost'
INFO:app.server:Initializing database port to '27017'
INFO:app.server:Creating private authentication key
DEBUG:app.server:Planner has started
DEBUG:asyncio:Using selector: EpollSelector
INFO:app.server:No SSL certificate or key found. Generating a self-signed SSL certificate for you.
Generating a RSA private key
INFO:app.updates:Updating logical definition of step: 'Credentials'
........+++++
...........+++++
writing new private key to 'conf/key.pem'
-----
DEBUG:asyncio:Using selector: EpollSelector
INFO:app.server:Serving on 0.0.0.0:8888
INFO:app.updates:Updating logical definition of step: 'PsexecMove'
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): download.sysinternals.com
DEBUG:urllib3.connectionpool:https://download.sysinternals.com:443 "GET /files/PSTools.zip HTTP/1.1" 200 2833224
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): attack-old.mitre.org
DEBUG:urllib3.connectionpool:https://attack-old.mitre.org:443 "GET /api.php?action=ask&format=json&query=%5B%5BCategory%3ATactic%5D%5D HTTP/1.1" 200 2110
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): attack-old.mitre.org
DEBUG:urllib3.connectionpool:https://attack-old.mitre.org:443 "GET /api.php?action=ask&format=json&query=%5B%5BCategory%3ATechnique%5D%5D%7C%3FHas+tactic%7C%3FHas+ID%7C%3FHas+display+name%7C%3FHas+technical+description%7C%3FHas+platform%7Climit%3D9999 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): attack-old.mitre.org
DEBUG:urllib3.connectionpool:https://attack-old.mitre.org:443 "GET /wiki/Template:Ordered_Tactics HTTP/1.1" 200 5629
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): attack-old.mitre.org
DEBUG:urllib3.connectionpool:https://attack-old.mitre.org:443 "GET /api.php?action=ask&format=json&query=%5B%5BCategory%3AGroup%5D%5D%7C%3FHas+ID%7C%3FHas+technique%7C%3FHas+alias%7Climit%3D9999 HTTP/1.1" 200 None

**Comment by teqagogo** [comment]
I'm closing the issue. Thank you
