### ISSUE TITLE
500 error code when request "/plugin/adversary/gui"

### ISSUE THREAD

**Issue by douwanhu** [mitre/caldera#899]
The caldera seems good, but when i access the plugin adversary I got an error code 500. I have turned on the debug which show the error info as below:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_middlewares.py", line 106, in impl
    return await handler(request)
  File "/usr/local/lib/python3.7/dist-packages/aiohttp_session/__init__.py", line 152, in factory
    response = await handler(request)
  File "/usr/local/lib/python3.7/dist-packages/aiohttp_jinja2/__init__.py", line 91, in wrapped
    context = await coro(*args)
  File "/root/Adversary/caldera/plugins/adversary/app/service/adversary_api.py", line 248, in planner
    techniques=con.get_techniques(),
  File "/root/Adversary/caldera/plugins/adversary/app/database/dao.py", line 24, in get_techniques
    return self.db.get_techniques(ids)
  File "/root/Adversary/caldera/plugins/adversary/app/database/mongo.py", line 59, in get_techniques
    return [self._map_technique(x) for x in self._query('technique', ids)]
  File "/root/Adversary/caldera/plugins/adversary/app/database/mongo.py", line 59, in <listcomp>
    return [self._map_technique(x) for x in self._query('technique', ids)]
  File "/usr/local/lib/python3.7/dist-packages/pymongo/cursor.py", line 1189, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.7/dist-packages/pymongo/cursor.py", line 1104, in _refresh
    self.__send_message(q)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/cursor.py", line 982, in __send_message
    helpers._check_command_response(first)
  File "/usr/local/lib/python3.7/dist-packages/pymongo/helpers.py", line 132, in _check_command_response
    raise NotMasterError(errmsg, response)
pymongo.errors.NotMasterError: node is not in primary or recovering state

**Comment by privateducky** [comment]
To use the adversary plugin, you’ll need to install the plugin (download it into the plugins directory). Then enable it via the conf/default.yml file.

**Comment by privateducky** [comment]
Note though: the adversary plugin is being deprecated, so I wouldn’t rely on it for future work.
