### ISSUE TITLE
Unable to start using either Docker option in instructions

### ISSUE THREAD

**Issue by Psibur** [mitre/caldera#92]
Running on a Red Hat 7.6 build and tried to run the docker-compose and docker build options with selinux enabled and disabled.  

When I run with **docker-compose up**, I get the following output:

```
caldera-master]# docker-compose up
Creating calderamaster_db_1     ... done
Creating calderamaster_db_1     ...
Creating calderamaster_server_1 ... done
Attaching to calderamaster_db_1, calderamaster_server_1
db_1      | 2019-01-08T15:14:58.350+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
db_1      | 2019-01-08T15:14:58.390+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=mongo
db_1      | 2019-01-08T15:14:58.390+0000 I CONTROL  [initandlisten] db version v4.0.5
db_1      | 2019-01-08T15:14:58.390+0000 I CONTROL  [initandlisten] git version: 3739429dd92b92d1b0ab120911a23d50bf03c412
db_1      | 2019-01-08T15:14:58.390+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
db_1      | 2019-01-08T15:14:58.390+0000 I CONTROL  [initandlisten] allocator: tcmalloc
db_1      | 2019-01-08T15:14:58.390+0000 I CONTROL  [initandlisten] modules: none
db_1      | 2019-01-08T15:14:58.390+0000 I CONTROL  [initandlisten] build environment:
db_1      | 2019-01-08T15:14:58.390+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
db_1      | 2019-01-08T15:14:58.390+0000 I CONTROL  [initandlisten]     distarch: x86_64
db_1      | 2019-01-08T15:14:58.390+0000 I CONTROL  [initandlisten]     target_arch: x86_64
db_1      | 2019-01-08T15:14:58.390+0000 I CONTROL  [initandlisten] options: { net: { bindIp: "0.0.0.0" }, replication: { replSet: "caldera" } }
db_1      | 2019-01-08T15:14:58.396+0000 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
db_1      | 2019-01-08T15:14:58.397+0000 I STORAGE  [initandlisten]
db_1      | 2019-01-08T15:14:58.397+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
db_1      | 2019-01-08T15:14:58.397+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
db_1      | 2019-01-08T15:14:58.397+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1383M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
db_1      | 2019-01-08T15:15:00.506+0000 I STORAGE  [initandlisten] WiredTiger message [1546960500:506449][1:0x7f881653ea40], txn-recover: Main recovery loop: starting at 4/6912 to 5/256
db_1      | 2019-01-08T15:15:00.721+0000 I STORAGE  [initandlisten] WiredTiger message [1546960500:721882][1:0x7f881653ea40], txn-recover: Recovering log 4 through 5
db_1      | 2019-01-08T15:15:01.438+0000 I STORAGE  [initandlisten] WiredTiger message [1546960501:438001][1:0x7f881653ea40], txn-recover: Recovering log 5 through 5
db_1      | 2019-01-08T15:15:01.554+0000 I STORAGE  [initandlisten] WiredTiger message [1546960501:554458][1:0x7f881653ea40], txn-recover: Set global recovery timestamp: 0
db_1      | 2019-01-08T15:15:01.759+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
db_1      | 2019-01-08T15:15:01.860+0000 I CONTROL  [initandlisten]
db_1      | 2019-01-08T15:15:01.860+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
db_1      | 2019-01-08T15:15:01.860+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
db_1      | 2019-01-08T15:15:01.860+0000 I CONTROL  [initandlisten]
db_1      | 2019-01-08T15:15:01.861+0000 I CONTROL  [initandlisten]
db_1      | 2019-01-08T15:15:01.861+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
db_1      | 2019-01-08T15:15:01.862+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
db_1      | 2019-01-08T15:15:01.862+0000 I CONTROL  [initandlisten]
db_1      | 2019-01-08T15:15:01.862+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
db_1      | 2019-01-08T15:15:01.862+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
db_1      | 2019-01-08T15:15:01.862+0000 I CONTROL  [initandlisten]
db_1      | 2019-01-08T15:15:01.926+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
db_1      | 2019-01-08T15:15:01.930+0000 I REPL     [initandlisten] Did not find local voted for document at startup.
db_1      | 2019-01-08T15:15:01.931+0000 I REPL     [initandlisten] Rollback ID is 1
db_1      | 2019-01-08T15:15:01.931+0000 I REPL     [initandlisten] Did not find local replica set configuration document at startup;  NoMatchingDocument: Did not find replica set configuration document in local.system.replset
db_1      | 2019-01-08T15:15:01.934+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
db_1      | 2019-01-08T15:15:01.935+0000 I CONTROL  [LogicalSessionCacheRefresh] Sessions collection is not set up; waiting until next sessions refresh interval: Replication has not yet been configured
db_1      | 2019-01-08T15:15:01.936+0000 I CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: config.system.sessions does not exist
server_1  | Traceback (most recent call last):
server_1  |   File "/opt/caldera/caldera/app/server.py", line 89, in run
server_1  |     with open(abs_conf_file_path, 'r') as f:
server_1  | FileNotFoundError: [Errno 2] No such file or directory: '/opt/caldera/caldera/app/../conf/settings.yaml'
server_1  |
server_1  | During handling of the above exception, another exception occurred:
server_1  |
server_1  | Traceback (most recent call last):
server_1  |   File "caldera.py", line 24, in <module>
server_1  |     server.run(debug=debug)
server_1  |   File "/opt/caldera/caldera/app/server.py", line 93, in run
server_1  |     with open(abs_conf_file_path, 'w') as c_f:
server_1  | PermissionError: [Errno 13] Permission denied: '/opt/caldera/caldera/app/../conf/settings.yaml'
calderamaster_server_1 exited with code 1
db_1      | 2019-01-08T15:20:01.935+0000 I CONTROL  [LogicalSessionCacheRefresh] Sessions collection is not set up; waiting until next sessions refresh interval: Replication has not yet been configured
db_1      | 2019-01-08T15:20:01.935+0000 I CONTROL  [LogicalSessionCacheReap] Sessions collection is not set up; waiting until next sessions reap interval: config.system.sessions does not exist

```
When I use the **docker build...** option (the rout I'd prefer to go), I get:

```
 caldera-master]# docker run --net=host caldera
INFO:app.server:Creating private key for database
INFO:app.server:Setting database host to 'localhost'
INFO:app.server:Initializing database port to '27017'
INFO:app.server:Creating private authentication key
Traceback (most recent call last):
  File "caldera.py", line 24, in <module>
    server.run(debug=debug)
  File "/opt/caldera/caldera/app/server.py", line 111, in run
    database.initialize(settings['database']['key'], settings['database']['host'], settings['database']['port'])
  File "/opt/caldera/caldera/app/engine/database.py", line 51, in initialize
    a = next(oplog.find().sort('$natural', pymongo.DESCENDING).limit(-1))['ts']
  File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1189, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python3.6/site-packages/pymongo/cursor.py", line 1087, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1558, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1511, in __start_session
    server_session = self._get_server_session()
  File "/usr/local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1544, in _get_server_session
    return self._topology.get_server_session()
  File "/usr/local/lib/python3.6/site-packages/pymongo/topology.py", line 427, in get_server_session
    None)
  File "/usr/local/lib/python3.6/site-packages/pymongo/topology.py", line 199, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused

```
I feel like I am either missing a step which is implied but maybe needs to be clarified in the instructions, or there is something else going on.

If I can get the steps mentioned on [https://caldera.readthedocs.io/en/latest/requirements.html](https://caldera.readthedocs.io/en/latest/requirements.html) which state there is a way to install Caldera without an internet connection, that would actually be what I need since I will have to eventually install this on an airgapped network.

**Comment by hf-mitre** [comment]
Hi @Psibur 

For docker-compose verify that the bind-mounted conf directory (`<caldera project dir>/caldera/conf`) is writeable by docker (probably 'root'). 

For just using `docker run --net=host caldera` check that there is properly configured (for caldera) MongoDB server running on the host that is available at `localhost:27017.  If there's not you can probably start this with docker too: `docker run --net=host -p 127.0.0.1:27017:27017 mongo --replSet caldera`
