### ISSUE TITLE
Settings --> ATT&CK Integration --> Load ATT&CK

### ISSUE THREAD

**Issue by workandresearchgithub** [mitre/caldera#98]
Pressing the button starts an attempt to download:
--
server_1  | DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): attack-old.mitre.org
--

Then apparently causes these errors:

--
server_1  | Traceback (most recent call last):
server_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
server_1  |     (self.host, self.port), self.timeout, **extra_kw)
server_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
server_1  |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
server_1  |   File "/usr/local/lib/python3.6/socket.py", line 745, in getaddrinfo
server_1  |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
server_1  | socket.gaierror: [Errno -2] Name or service not known
server_1  | 
server_1  | During handling of the above exception, another exception occurred:
server_1  | 
server_1  | Traceback (most recent call last):
server_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
server_1  |     chunked=chunked)
server_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
server_1  |     self._validate_conn(conn)
server_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
server_1  |     conn.connect()
server_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
server_1  |     conn = self._new_conn()
server_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
server_1  |     self, "Failed to establish a new connection: %s" % e)
server_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7ff78e7cfba8>: Failed to establish a new connection: [Errno -2] Name or service not known
server_1  | 
server_1  | During handling of the above exception, another exception occurred:
server_1  | 
server_1  | Traceback (most recent call last):
server_1  |   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
server_1  |     timeout=timeout
server_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
server_1  |     _stacktrace=sys.exc_info()[2])
server_1  |   File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
server_1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
server_1  | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='attack-old.mitre.org', port=443): Max retries exceeded with url: /api.php?action=ask&format=json&query=%5B%5BCategory%3ATactic%5D%5D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff78e7cfba8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
server_1  | 
server_1  | During handling of the above exception, another exception occurred:
server_1  | 
server_1  | Traceback (most recent call last):
server_1  |   File "/opt/caldera/caldera/app/api.py", line 122, in entrypoint
server_1  |     resp = await decorated(req, token, req.match_info)
server_1  |   File "/opt/caldera/caldera/app/api.py", line 84, in decorated
server_1  |     results = await f(req, **kwargs)
server_1  |   File "/opt/caldera/caldera/app/api.py", line 627, in load_attack
server_1  |     attack.refresh_attack()
server_1  |   File "/opt/caldera/caldera/app/attack.py", line 12, in refresh_attack
server_1  |     tactic_results = grab_site("{}/{}".format(attack_url, 'api.php'), params=params, stream=False, mode='attack').json()
server_1  |   File "/opt/caldera/caldera/app/util.py", line 124, in grab_site
server_1  |     return requests.get(site, params=params, proxies=proxies, verify=cert, stream=stream)
server_1  |   File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 75, in get
server_1  |     return request('get', url, params=params, **kwargs)
server_1  |   File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 60, in request
server_1  |     return session.request(method=method, url=url, **kwargs)
server_1  |   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 524, in request
server_1  |     resp = self.send(prep, **send_kwargs)
server_1  |   File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 637, in send
server_1  |     r = adapter.send(request, **kwargs)
server_1  |   File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
server_1  |     raise ConnectionError(e, request=request)
--

And fails with this error:
--
server_1  | requests.exceptions.ConnectionError: HTTPSConnectionPool(host='attack-old.mitre.org', port=443): Max retries exceeded with url: /api.php?action=ask&format=json&query=%5B%5BCategory%3ATactic%5D%5D (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff78e7cfba8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
--

**Comment by cl-mitre** [comment]
Hey, thanks for submitting this. This is actually addressed in issue #96, and is linked to the fact that the attack-old.mitre.org website was depreciated recently. A new build that we plan on open-sourcing in the future will account for this by pulling information from newer ATT&CK resources. In the mean time, you should be able to use CALDERA without issue without needing to update ATT&CK.
